### ISSUE TITLE
 Global variable switch error like #40 

### ISSUE THREAD

**Issue by naspinec** [ilcato/homebridge-fibaro-home-center#100]
Hello,

When I use Global Variables as switches I get one error saying : "There was a problem setting variable:  ABSENT to true"

In homekit the button switch to On but after a few seconds switch bask to Off.

Regards

**Comment by ilcato** [comment]
@naspinec, which version of the plugin do you use ?

**Comment by naspinec** [comment]
I tried 1.2.8 and added admin credentials and it worked correctly.

**Comment by ilcato** [comment]
good
