### ISSUE TITLE
Some Devices missing or not updated

### ISSUE THREAD

**Issue by miwa4711** [ilcato/homebridge-fibaro-home-center#106]
Hi,

using HB within Iobroker  to connect my Fibaro HC2 (ca. 130 Z-Wave Devices). Unfortunately some fibaro devices are not polled (e. g. smart implant with tempSensor DS18B20, DI of RGB-W Modul)  while same device types are detected correctly. Also some values will not be updated. Devices work fine in HC2. 
[config.txt](https://github.com/ilcato/homebridge-fibaro-home-center/files/9376121/config.txt)

Any idea?

Thanks
Michael

**Comment by mkz212** [comment]
Please fill #157
