### ISSUE TITLE
Change class of Fibaro roller shutter 2 to garage door instead of blind homebridge-fibaro-home-center

### ISSUE THREAD

**Issue by RikBast** [ilcato/homebridge-fibaro-home-center#107]
Hi,

I use roller shutter 2 as controller of a cargate, however in homebridge it is seen as ‘window covering’ class. Can it be changed to ‘garage’ as device class?

The goal is to make the gate visible in Apple CarPlay dashboard

thx,
Rik

**Comment by RikBast** [comment]
@ilcato did you have time to look into this? I now changed the Fibaro roller shutter 2 from 'blind with positioning' to 'gate with positioning' within Homecenter 2 after installing IR-barrier (sensor) to the garage door. I removed the garage door from homebridge and added it again, still it shows up as 'window covering' and not as 'garage door'. Anything else I could try to make it show up as garage door? Thx!

**Comment by ilcato** [comment]
@RikBast can you post the device descriptor coming from the Fibaro API?

**Comment by RikBast** [comment]
Here you go :-)

  {
    "id": 13,
    "name": "Garagepoort 2",
    "roomID": 227,
    "type": "com.fibaro.FGRM222",
    "baseType": "com.fibaro.FGR",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 12,
    "remoteGatewayId": 0,
    "viewXml": false,
    "configXml": false,
    "interfaces": [
      "deviceGrouping",
      "energy",
      "fibaroFirmwareUpdate",
      "levelChange",
      "power",
      "zwave",
      "zwaveMultiChannelAssociation",
      "zwaveProtection",
      "zwaveSceneActivation"
    ],
    "properties": {
      "pollingTimeSec": 0,
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,3,52",
      "zwaveVersion": "26.26",
      "RFProtectionState": "0",
      "RFProtectionSupport": "3",
      "categories": "[\"gates\"]",
      "configured": true,
      "dead": "false",
      "deadReason": "",
      "deviceControlType": "57",
      "deviceGroup": "[]",
      "deviceGroupMaster": "0",
      "deviceIcon": "49",
      "emailNotificationID": "0",
      "emailNotificationType": "0",
      "endPointId": "0",
      "energy": "1.63",
      "firmwareUpdate": "{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"26.26\"}",
      "localProtectionState": "0",
      "localProtectionSupport": "5",
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": "true",
      "model": "",
      "nodeId": "3",
      "parametersTemplate": "721",
      "power": "0.70",
      "productInfo": "1,15,3,2,16,0,26,26",
      "protectionExclusiveControl": "0",
      "protectionExclusiveControlSupport": "false",
      "protectionState": "0",
      "protectionTimeout": "0",
      "protectionTimeoutSupport": "false",
      "pushNotificationID": "0",
      "pushNotificationType": "0",
      "remoteGatewayId": "0",
      "saveLogs": "true",
      "sceneActivation": "0",
      "serialNumber": "",
      "showEnergy": "true",
      "smsNotificationID": "0",
      "smsNotificationType": "0",
      "state": "Unknown",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0",
      "value2": "0"
    },
    "actions": {
      "abortUpdate": 1,
      "close": 0,
      "open": 0,
      "reconfigure": 0,
      "reset": 0,
      "retryUpdate": 1,
      "sceneActivationSet": 0,
      "setValue": 1,
      "setValue2": 1,
      "startLevelDecrease": 0,
      "startLevelIncrease": 0,
      "startUpdate": 1,
      "stop": 0,
      "stopLevelChange": 0,
      "updateFirmware": 1
    },
    "created": 1675603767,
    "modified": 1675603767,
    "sortOrder": 22
  }

**Comment by ilcato** [comment]
@RikBast, can you confirm that "deviceControlType": "57" correspond to blind with positioning'?
Can you make some tests and understand which values can assume deviceControlType for your device ? (I don't have anymore this kind of devices).

**Comment by RikBast** [comment]
I have the following options for the Fibaro roller shutter:

"deviceControlType": "53" = Blind with positioning inactive
"deviceControlType": "54" = Blind with positioning active
"deviceControlType": "55” = Venetian Blind
"deviceControlType": "56” = Garage door without positioning
"deviceControlType": "57" = Garage door with positioning

**Comment by ilcato** [comment]
@RikBast can you test version `homebridge-fibaro-home-center@1.2.17-beta.0` ?

**Comment by ilcato** [comment]
@RikBast are you sure that the beta installed correctly? Did you restart homebridge?

**Comment by ilcato** [comment]
@RikBast, found the error can you test beta.1 ?

**Comment by RikBast** [comment]
@ilcato, this one works :-)

**Comment by ilcato** [comment]
@RikBast, I don't know when I will publish in production. Need to test other things.

**Comment by RikBast** [comment]
@ilcato, When opening from Fibaro HC2, the status is not updated in the home app

**Comment by ilcato** [comment]
@RikBast are you to check with the Fibaro API `refreshStates` action on Home Center are generated ?

**Comment by RikBast** [comment]
@ilcato, Not sure how that functions, but the normal blinds report status back from the HC2 to the home app, just the garage doors don't. I do see in the logging the Fibaro ID's and that these are updated, but it's not graphical visible on the accessories page and the home app

**Comment by ilcato** [comment]
@RikBast can you test beta.2 ?

**Comment by RikBast** [comment]
Installed got 2 warnings:

[30/03/2023, 07:01:45] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Current Position': Characteristic not in required or optional characteristic section for service GarageDoorOpener. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.

After clearing cache this one:

[Garagepoort 2@Garagepoort 2@Hold Position] Characteristic not in required or optional characteristic section for service GarageDoorOpener. Adding anyway.

**Comment by ilcato** [comment]
@RikBast, ok cannot use position.
In json you posted there a property: `"state": "Unknown",`
can you try to capture the state property while opening or closing?

**Comment by RikBast** [comment]
Yes, I will try tonight to get the status while opening and closing

**Comment by ilcato** [comment]
yes, garage door openers have only:
`CurrentDoorState
 TargetDoorState
ObstructionDetected
`
DoorState may assume several values that I map to device state. But if state is always unknown it is not useful.

**Comment by RikBast** [comment]
@ilcato , when opening 'state' remains 'unknown', but 'value' =  99 

      "state": "Unknown",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "99",
      "value2": "0"

When closing 'value' = 0, 'state' remains 'unknown'

      "state": "Unknown",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0",
      "value2": "0"

**Comment by RikBast** [comment]
> And the big question if the garage doors will start to appear in Apple CarPlay when reaching my home. I don't know what is responsible for that to appear, only the fact that it should be a garagedoor or is there anything else necessary? I haven't find more useful info yet, just that it seems possible:-)

This works by the way, the garage door pops up when Approaching the house in CarPlay, nice feature

**Comment by ilcato** [comment]
> ```
>   @ilcato , when opening 'state' remains 'unknown', but 'value' =  99 
> 
>   "state": "Unknown",
>   "updateVersion": "",
>   "useTemplate": "true",
>   "userDescription": "",
>   "value": "99",
>   "value2": "0"
> ```
> 
> 
>      
>   
> 
> When closing 'value' = 0, 'state' remains 'unknown'
> 
> 
> ```
>   "state": "Unknown",
>   "updateVersion": "",
>   "useTemplate": "true",
>   "userDescription": "",
>   "value": "0",
>   "value2": "0"
> ```
> 
> 
>      
>   
> 
> Garage door status not updated when opening/closing from HC2

And what about value when stopped?

**Comment by RikBast** [comment]
When stopped opening:

      "state": "Unknown",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0",
      "value2": "0"

When stopped closing:

      "state": "Unknown",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0",
      "value2": "0"

so nothing in 'state'

**Comment by ilcato** [comment]
@RikBast, I would need `refreshState` output.

 Anyway can you try beta.3 ?

**Comment by RikBast** [comment]
@ilcato, will look up the refreshState output tonight.

Meanwhile Installed beta 3:
[31/03/2023, 06:58:20] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://homebridge.io/w/JtMGR for more info.
[31/03/2023, 06:58:20] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1. See https://homebridge.io/w/JtMGR for more info.

**Comment by ilcato** [comment]
Can you test  beta.4?

**Comment by RikBast** [comment]
@ilcato, installed beta:    

I stopped garage door at 56%

{
      "id": 116,
      "RFProtectionSupport": "3",
      "categories": "[\"gates\"]",
      "configured": "true",
      "deviceControlType": "57",
      "energy": "13.66",
      "localProtectionSupport": "5",
      "log": "",
      "logTemp": "",
      "parameters": "[{\"id\":3,\"size\":1,\"value\":0},{\"id\":10,\"size\":1,\"value\":4},{\"id\":12,\"size\":2,\"value\":0},{\"id\":13,\"size\":1,\"value\":1},{\"id\":14,\"size\":1,\"value\":0},{\"id\":17,\"size\":1,\"value\":0},{\"id\":18,\"size\":1,\"value\":10},{\"id\":22,\"size\":2,\"value\":240},{\"id\":29,\"size\":1,\"value\":1},{\"id\":30,\"size\":1,\"value\":2},{\"id\":31,\"size\":1,\"value\":0},{\"id\":32,\"size\":1,\"value\":0},{\"id\":33,\"size\":1,\"value\":0},{\"id\":35,\"size\":1,\"value\":1},{\"id\":40,\"size\":1,\"value\":10},{\"id\":42,\"size\":2,\"value\":3600},{\"id\":43,\"size\":1,\"value\":10},{\"id\":44,\"size\":1,\"value\":1},{\"id\":50,\"size\":1,\"value\":0}]",
      "power": "0.70",
      "value": "56"
    },

<img width="785" alt="Scherm­afbeelding 2023-03-31 om 17 34 38" src="https://user-images.githubusercontent.com/81705450/229165675-a2209faa-eb32-41aa-af38-ef163545b017.png">

<img width="350" alt="Scherm­afbeelding 2023-03-31 om 17 34 47" src="https://user-images.githubusercontent.com/81705450/229165730-2312e0fb-e1ab-4b6d-8c49-48550fa58e26.png">

Homekit reports 'stopped', but doesn't at which value apparently

**Comment by RikBast** [comment]
@ilcato, is the integration ok now you think? the beta 4 works fine. Open/Close status nicely reported. In between states not possible for HomeKit garage doors.
Thx for your help!

**Comment by ilcato** [comment]
@RikBast, just published 1.2.17 in production.

**Comment by RikBast** [comment]
> @RikBast, just published 1.2.17 in production.

Thank you for this.

**Comment by RikBast** [comment]
Hi, still a small issue. When garage door is opened manually with pushbutton, the status in Homekit of the garage door is 'stopped' and not 'Open'. So in Homekit the garage door remains closed/stopped status instead of Open status
