### ISSUE TITLE
Fix service type for Wall Socket binarySwitch

### ISSUE THREAD

**Issue by lboue** [ilcato/homebridge-fibaro-home-center#115]
Wall Socket deviceControlType: "20" should be exposed to HomeKit as Outlet.
I pushed the PR #114 to fix that issue.

**Comment by lboue** [comment]
Fixed with 1.2.10

**Comment by lboue** [comment]
There are 2 accessories published instead of just one.
Wall Socket/Outlet is exposed but we also have a switch 

![IMG-9572](https://user-images.githubusercontent.com/938089/190163377-0dfd352d-623b-4bd6-9062-59f636bff6ba.jpg)

**Comment by ilcato** [comment]
@lboue which app are you using ?

**Comment by lboue** [comment]
I am using [Controller for HomeKit 4+](https://apps.apple.com/us/app/controller-for-homekit/id1198176727)

**Comment by lboue** [comment]
Maybe OutletInUse have to be set as **additional** Characteristic and not **main**Characteristics.

`this.mainCharacteristics = [this.platform.Characteristic.On, this.platform.Characteristic.OutletInUse];
`

**Comment by mkz212** [comment]
See #157. You must remove unused devices from cache (Homebridge Settings).
