### ISSUE TITLE
IOS16 Device Type Groups

### ISSUE THREAD

**Issue by mol7os** [ilcato/homebridge-fibaro-home-center#117]
Hi,

in my combination with Fibaro HC3, Homebridge/Plugin (all latest SW Version) it seems that the Fibaro Devices are sometimes grouped in the wrong categories. Checking the "central settings" all roller shutters are listed as such, but on the home screen, they are grouped within the favorite group "Climatic". 
Is there anything how I can influence this kind of grouping on my own? In HC3 all devices are tagged as Blinds and real climatic devices as air conditioners.

**Comment by ilcato** [comment]
@mol7os not sure to understand what you are saying. Can you attach some screenshots ?

**Comment by mol7os** [comment]
Other Devices can be edited (Icon) which will then influence the categorization. 
(Example a Switch: Switch/Light/Ventilator -> as light they will be grouped in the category "lights", as Switch they don´t have a predefined category in homekit).

![IMG_5787 14795](https://user-images.githubusercontent.com/26004218/190332516-7a80bcf0-bac8-4d4f-9f4e-7a4893cbbc43.jpg)

Maybe it´s a current bug in Homkit IOS16, but if not, and things were changed in the background I want to mention this finding.

**Comment by mol7os** [comment]
"Filter" Climatic (Klima) is chosen, and as you can see Roller Shutter devices are on that filter list. Fibaro Roller Shutter 2 in this case.

**Comment by lboue** [comment]
I noticed the same behavior since iOS16 for me.

**Comment by mkz212** [comment]
It depends on Apple, not this plugin. You should report to Apple.
