### ISSUE TITLE
Error: getaddrinfo ENOTFOUND hc3-000XXXXX.local

### ISSUE THREAD

**Issue by PetrHuu** [ilcato/homebridge-fibaro-home-center#120]
Hello, I try to install homebridge on my Synology. I copied the certificate from my HC3 to /homebridge, but after restarting, I got the error:

[10/26/2022, 9:26:35 PM] [HC3-000XXXXX] Error getting data from Home Center:  Error: getaddrinfo ENOTFOUND hc3-000XXXXX.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hc3-000XXXXX.local',
  response: undefined
}
Error: getaddrinfo ENOTFOUND hc3-000XXXXX.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
[10/26/2022, 9:26:35 PM] [HC3-000000XXXXX] Child bridge process ended

Btw, the address https://hc3-000XXXXX.local usually works in the browsers. Please, have you any idea?

Thank you,
Petr

**Comment by ilcato** [comment]
@PetrHuu, try the IP address instead of local address. Probably the synology is not able to translate it.

**Comment by baduxiyang** [comment]
更新: homebridge
Release Notes
v.1.6.1
What's Changed
Bug Fixes 🐛
Fixed an issue with the avahi advertiser on Synology that resulted in homebridge not starting by @Supereg in https://github.com/homebridge/HAP-NodeJS/pull/1003
Resolved an issue where developers weren't able to compile strict TypeScript projects against Homebridge
Full Changelog: https://github.com/homebridge/homebridge/compare/v1.6.0...v1.6.1
