### ISSUE TITLE
No thermostats are displayed

### ISSUE THREAD

**Issue by Berti321** [ilcato/homebridge-fibaro-home-center#125]
Hello unfortunately no thermostats are displayed in the Homebridge, maybe someone has an idea what it can be? They are Danfoss thermostats. thanks for the help

**Comment by RobBoijmans** [comment]
Hi, same problem here with same thermostats. Who can help? Thanks

**Comment by maoten2000** [comment]
any clue about this issue? no actual or quick app thermostat is showing!.
Please advise @ilcato .

**Comment by Tymo3** [comment]
Any plans to support it? Or any workarounds?

**Comment by JameStitel** [comment]
Thermostats were suppported in homebridge-fibaro-hc3 v1.1.14. Now I switched to homebridge-fibaro-home-center v1.2.20 as it seems the other is not supported anymore, but the Fibaro thermostats are gone??

**Comment by mkz212** [comment]
Please fill #157
