### ISSUE TITLE
Remotes exposed?

### ISSUE THREAD

**Issue by JameStitel** [ilcato/homebridge-fibaro-home-center#131]
Hi, are remotes from Home Center exposed to Homekit?

![Screenshot 2023-02-19 at 11 27 16 PM](https://user-images.githubusercontent.com/22136829/219978902-73738708-3f5d-4f94-9fe9-fa178ae935d0.png)
![Screenshot 2023-02-19 at 11 27 08 PM](https://user-images.githubusercontent.com/22136829/219978904-e7074405-3347-4c1d-8e9c-8101cefccdbc.png)

**Comment by mkz212** [comment]
What would be the purpose of such a solution?
