### ISSUE TITLE
Elero Roller Shutters do show up as Garage doors

### ISSUE THREAD

**Issue by joystick666** [ilcato/homebridge-fibaro-home-center#134]
I just switched to HC3, and until now only implemented my Elero roller shutters,
unfortunately they do not show up in HB.

What can I do to help here?

cheers

**Comment by dsylex** [comment]
@joystick666 did you manage to solve it somehow? I also use elero rollers

**Comment by joystick666** [comment]
@dyslex yeah, I just did a fresh install of the extension , and the Rollershutters showed up. 
I have Elero Roltop rollers btw. Maybe some others do not work…?

**Comment by dsylex** [comment]
> @Dyslex yeah, I just did a fresh install of the extension , and the Rollershutters showed up.
> I have Elero Roltop rollers btw. Maybe some others do not work…?

I have the same rollers. Problem is that I can’t even get the plugin to work let alone have the rollers show up in HB. I posted the logs in issue #133 but the dev of the plugin seems inactive.

**Comment by dsylex** [comment]
> @Dyslex yeah, I just did a fresh install of the extension , and the Rollershutters showed up.
> I have Elero Roltop rollers btw. Maybe some others do not work…?

I have the same rollers. Problem is that I can’t even get the plugin to work let alone have the rollers show up in HB. I posted the logs in issue #133 but the dev of the plugin seems pretty inactive.

**Comment by joystick666** [comment]
Did it work in the past? I read somewhere that Yubii home Box had issue in connection with home bridge...

**Comment by dsylex** [comment]
> Did it work in the past? I read somewhere that Yubii home Box had issue in connection with home bridge...

I got them to work just now by removing the plugin and reinstalling. They show up in HomeKit but as Garage doors. I can open and close them but cannot stop them. Do they work and show up as blinds for you?

**Comment by joystick666** [comment]
Yes, they show up as Garage doors, for me aswell. Same behavior as yours, which is not the crucial for me, though.

**Comment by dsylex** [comment]
> Yes, they show up as Garage doors, for me aswell. Same behavior as yours, which is not the crucial for me, though.

Ah, shame. I do want to change positioning as well though, which is not possible if it only handles open/closed states.

**Comment by dsylex** [comment]
is the dev still active or did they abandon this project? No updates and info from @ilcato since nov 2022

**Comment by joystick666** [comment]
> > Yes, they show up as Garage doors, for me aswell. Same behavior as yours, which is not the crucial for me, though.
> 
> Ah, shame. I do want to change positioning as well though, which is not possible if it only handles open/closed states.


> is the dev still active or did they abandon this project? No updates and info from @ilcato since nov 2022

IDK, but he was very active in the past, though

**Comment by joystick666** [comment]
I saw you opened an issue, thus I closed mine. Ilcato was active in February...so lets hope he is still around

**Comment by mkz212** [comment]
@joystick666 @dsylex If the problem still occurring then put on a new thread. Work on the new version is underway. Before submitting, read the Troubleshooting sections on the main page of the plugin. Thanks!
