### ISSUE TITLE
turn everything on for not understanding the order

### ISSUE THREAD

**Issue by itsirc20066** [ilcato/homebridge-fibaro-home-center#140]
Hello, I am testing on the hc3, and there is an error when used with siri, for example, turn on lamp x if the lamp x is not there or you have not understood it correctly, it turns out that it turns on everything, with previous versions that did not happen, is there a solution? ?

**Comment by mkz212** [comment]
Apple change something in iOS 17. It has nothing to do with the plugin. 

I noticed that previous was working command:  "Hey Siri Lamp X" where Lamp X is just a device name. I didn't even have to say turn on or turn off. Now I have to say Hey Siri ROOM-NAME COMMAND DEVICE-NAME E.G.: "Hey Siri Kitchen turn on Lamp".
