### ISSUE TITLE
JSON error on init

### ISSUE THREAD

**Issue by sadovsf** [ilcato/homebridge-fibaro-home-center#141]
Hello, recently plugin started failing on init which results in whole homebridge not booting up (I have only this plugin installed). Here is log around error part:

![image](https://user-images.githubusercontent.com/2211533/235295114-cef3ccfa-4355-4499-96c7-7917dd76a3de.jpeg)

Plugin version 1.1.14, tried with 1.1.13 but it did not help.

Homebridge version 1.6.0

**Comment by ilcato** [comment]
@sadovsf do you still have this problem?

**Comment by sadovsf** [comment]
Seems some update fixed it. Will let you know in case it happens again.
