### ISSUE TITLE
Add room name to devices

### ISSUE THREAD

**Issue by Franco268** [ilcato/homebridge-fibaro-home-center#150]
When I switch the option from enable to disabled (or removing the option).

I got that issue: "Error getting data from Home Center:  Error: Cannot Bridge more than 149 Accessories" then the secondary bridge restart.

**Comment by ilcato** [comment]
@Franco268, how many devices do you have?

**Comment by ilcato** [comment]
@Franco268, try using a child bridge

**Comment by Franco268** [comment]
89 devices and i'm using a child bridge.
I removed then added the pluging and now it works fine.
In the Home app, I was able to see all of my devices but without status. And in the "default room", the copy of all devices but with the updated status. Basicaly everithing was doubled.

**Comment by ilcato** [comment]
@Franco268, I think you must delete the old accessories created with initial  setup

**Comment by jurassiksame** [comment]
Hi I have the same issue, I have 98 devices, but  it exposes more than 149 devices, and gives error… I have the child on, on the plug-in but the plug-in led, stays green for 1-2 seconds and turns red it’s always on this, any help?

very thanks

**Comment by jurassiksame** [comment]
No help on this?

**Comment by mkz212** [comment]
Try remove from cache unused devices (in Homebridge Settings).
