### ISSUE TITLE
Aeotec wallmote 

### ISSUE THREAD

**Issue by jurassiksame** [ilcato/homebridge-fibaro-home-center#154]
Hi it’s possible to add Aeotec wallmote to plug-in?

regards

**Comment by ilcato** [comment]
Can you tell me the type value of the device ?

**Comment by ilcato** [comment]
@mkz212 can you have a look at this?

**Comment by mkz212** [comment]
@ilcato I propose to add a pinned post, with instructions on how to get an API response so that everyone who wants to add a new device type provides the necessary data, i.e. "type" i "deviceControlType".

**Comment by ilcato** [comment]
> @ilcato I propose to add a pinned post, with instructions on how to get an API response so that everyone who wants to add a new device type provides the necessary data: "type" i "deviceControlType".

build it!

**Comment by jurassiksame** [comment]
Hi Guys very thanks for the replay.

About : http://FIBARO-IP/api/devices/

show me something like this:

<img width="1371" alt="Captura de ecrã 2023-11-09, às 21 47 54" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/149274289/4e8cd3d8-4722-41d2-aa05-0c949bb6e81e">


about the: "deviceControlType" (it will be number). its 132 correct ?

about:  "type" here I found:

<img width="1030" alt="Captura de ecrã 2023-11-09, às 21 48 38" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/149274289/c643367b-69af-4250-9f77-eb8b85e58039">

i have more device as note exposed I will send to the new post you add, after I know I can get the correct information.

very thanks

**Comment by mkz212** [comment]
@jurassiksame send only part about device you want - text, no image.

**Comment by mkz212** [comment]
#157 Here you have a more accurate instruction and example

**Comment by jurassiksame** [comment]
Hi @mkz212 :

This is all information you need ?

"id":1142,"name":"Interruptor","roomID":233,"type":"com.fibaro.remoteController","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":0,"remoteGatewayId":5,"viewXml":false,"configXml":false,"remoteGatewayId":5,"interfaces":["battery","fibaroFirmwareUpdate","remoteGateway","zwave","zwaveAlarm","zwaveCentralScene","zwaveMultiChannelAssociation","zwaveWakeup"],"properties":{"alarmLevel":"0","alarmType":"0","batteryLevel":"255","batteryLowNotification":"true","categories":"[\"remotes\"]","centralSceneSupport":"[{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":1},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":2},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":3},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":4}]","configured":true,"dead":"false","deadReason":"","defInterval":"0","deviceControlType":"0","deviceIcon":"103","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","firmwareUpdate":"{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"2.3\"}","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"27","parameters":[],"parametersTemplate":"0","pollingTimeSec":0,"productInfo":"0,134,0,2,0,130,2,3","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","updateVersion":"","useTemplate":"false","userDescription":"","wakeUpTime":0,"zwaveCompany":"AEON Labs","zwaveInfo":"3,4,62","zwaveVersion":"2.3"},"actions":{"abortUpdate":1,"reconfigure":0,"retryUpdate":1,"setInterval":1,"startUpdate":1,"updateFirmware":1},"created":1699213060,"modified":1699213060,"sortOrder":650},{"id":1143,"name":"Sensor
