### ISSUE TITLE
The heat controller is not appearing in home app.

### ISSUE THREAD

**Issue by Tangheta** [ilcato/homebridge-fibaro-home-center#155]
After some years, giving the Fibaro z-wave heat controller a go again to control a single radiator.

But it does not show up in the home app. 
only a temperature sensor is added.

see also https://github.com/ilcato/homebridge-Fibaro-HC2/issues/92

**Comment by ilcato** [comment]
I do not support single controller anymore.
Please define an heat zone in Fibaro, it will appear as a thermostat in homekit.

**Comment by Tangheta** [comment]
Awesome. Thanks!
