### ISSUE TITLE
Fibaro plug appears as 2 devices

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#159]
Hi ilcato,

after the latest update, I'm seeing some of my Fibaro Plug appearing as 2 devices in Home app (not all of them though). Can you tell me why this is happening?

<img width="264" alt="Screenshot 2023-11-10 alle 10 25 37" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/9434736/91a4fede-e491-42d8-98e7-d49d25309d33">

**Comment by ilcato** [comment]
@mkz212 can you have a look? I think the issue is in the new outlet wall plug logic you implemented. Unfortunately I do not have anymore such devices.

**Comment by mkz212** [comment]
@ilcato @redeemer666 Nothing of the sort occurs for me (on two independent devices and smart homes). Some time ago I also had such a thing (but with lights). And I think I had to clean the device from the cache (Homebridge Settings). Please let me know if it helped.

**Comment by ilcato** [comment]
@redeemer666 how do you classify the plug within Home Center (Category and Role). Maybe the new implementation assign it to a diffferent accessory type within homekit and now you have both the old representation and the new one.
As @mkz212 said try to selectively remove from the accessory cache the accessory and restart homebridge.

**Comment by mkz212** [comment]
@redeemer666 Are both of these devices active? I.e. do both actually work? If only one works, you most likely have to remove unnecessary from the cache.

**Comment by redeemer666** [comment]
OK deleting the accessory from the cache doesn't make it reappear as "duplicated", but it recognize it as a switch, not a plug. Not a problem, just the image in home app is not correct

**Comment by mkz212** [comment]
@redeemer666 In Fibaro, when you login, and go to this device, find field ROLE where you select What does the device control. 

If you choose there:
- Light - it will be Light,
- "Other" will be Switch,
- Sprinkler or Valve will be a Valve
- in any other case: Outlet

**Comment by redeemer666** [comment]
> @redeemer666 In Fibaro, when you login, and go to this device, find field ROLE where you select What does the device control.
> 
> If you choose there:
> 
> * Light - it will be Light,
> * "Other device" will be Switch,
> * Sprinkler or Valve will be a Valve
> * in any other case: Outlet
> 
> Note: You must remove from cache (Homebridge settings) to see effect.

Maybe this was the reason why they appear as double and the third one was correct. Converted all "Roles" as "TV set" and they appear as outlet now (after removing again from Homebridge). Thanks guys, as usual best of the best

**Comment by redeemer666** [comment]
Closing this since the issue was not a real issue 👍 Thanks again

**Comment by mkz212** [comment]
Previously, there was no choice for devices such as Wall Plug. And e.g. Smart Implant or Double Switch had such a possibility. Wall Plug, on the other hand, always displayed as a Outlet. But a lot of people use a wall plug to control a valve or light or else.
