### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by mkz212** [ilcato/homebridge-fibaro-home-center#161]
@ilcato I think you can do a little cleaning (close the Issues):

#52 - outdated, and I think the problem is already solved, if not then pinned post
#72 - outdated, and I think the problem is already solved
#76 - outdated
#80 - outdated
#86 - outdated
#87 - outdated and without answer
#88 - outdated
#94 - outdated and i think solved
#96 - outdated / new device type - pinned post
#97 - outdated
#101 - outdated
#106 - outdated / new device type - pinned post
#113 - outdated
#115 - outdated and i think solved
#117 - solved
#120 - solved
#123 - outdated
#125 - new device type - pinned post
#126 - outdated
#127 - outdated / new device type - pinned post
#129 - outdated
#131 - outdated / new device type - pinned post
#140 - solved
#150 - I think solved 
#154 - new device type - pinned post

To check:
#108 - not sure? is it solved?
#111 - not sure? is it solved?
#141 - outdated but solved?
#149 - outdated and I don't know what in this case? Are you going to introduce something like this and is it possible at all (homekit restrictions)?
#153 - i made PR for this, not sure it will help

P.S.: I think you can somehow set to automatically close outdated Issues.

**Comment by mkz212** [comment]
@ilcato I also think that in the changelog of the next update as well as to the troubleshoting page you can add info that if the device is displayed incorrectly or doubly, user should first clean it from the cache (Homebridge settings).

**Comment by ilcato** [comment]
@mkz212 cleaned.
Will check the remaining later.
Thanks
