### ISSUE TITLE
Single Switches appear as two devices: Light + Switch

### ISSUE THREAD

**Issue by Krillle** [ilcato/homebridge-fibaro-home-center#163]
Switches, which used to be one single device, now show up in Homebridge and Home App as two devices.

The switch was shown wrongly as light in v1.2.20. This home device is not connected to the Fibaro device any more.
Now it has beed added additionally as a switch. The new switch is switching the actual Fibaro device.

First realized in version v 1.4.0
Might be a side effect of the fix of a previous issue.

**Konfiguration**
Homebridge v1.7.0
homebridge-fibaro-home-center v1.4.0
Node.js v18.16.0
Raspbian GNU/Linux Bullseye (11)
Fresh Install on Raspberry Pi 3+
Home Center 2 v4.630

Screenshot from my Home App. Left device is original device. Second device is new. 
<img width="317" alt="Bildschirmfoto 2023-11-11 um 10 05 53" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/2863110/59d7bf94-faf5-4f4a-b725-c1a27b6db717">

**Comment by mkz212** [comment]
@Krillle you must remove unused device from cache (Homebridge settings)

**Comment by Krillle** [comment]
Removing device from cache in Homebridge Settings fixed the issue. Device was added correctly automatically.
