### ISSUE TITLE
Rollershutter3 not recognised as gate anymore

### ISSUE THREAD

**Issue by RikBast** [ilcato/homebridge-fibaro-home-center#173]
Since latest update the rollershutter3 isn't recognised as gate anymore, so will not show up in CarPlay.
In version 1.4.0 it works, but not in 1.4.1 and the latest beta

**Comment by ilcato** [comment]
@mkz212 can you have a look?

**Comment by mkz212** [comment]
@RikBast please attach API response for this device. How to get API response for device: Open in browser: http://fibaro-ip/api/devices/ID (replace FIBARO-IP with your Home Center IP and ID with device ID) and login.

**Comment by mkz212** [comment]
@RikBast should be fixed in next beta. Thank you. If next beta fix this please close issue. Anyway, please attach response from API for this device.

**Comment by RikBast** [comment]
Hi,

As  requested, the API response for the rollershutter3 device:

{"id":454,"name":"Garagepoort 1","roomID":229,"view":[{"assetsPath":"dynamic-plugins/com.fibaro.rollerShutter","name":"com.fibaro.rollerShutter","translatesPath":"/assets/i18n/com.fibaro.rollerShutter","type":"ts"},{"assetsPath":"dynamic-plugins/energy","name":"energy","translatesPath":"/assets/i18n/energy","type":"ts"},{"assetsPath":"dynamic-plugins/favorite-positions","name":"favorite-positions","translatesPath":"/assets/i18n/favorite-positions","type":"ts"},{"assetsPath":"dynamic-plugins/power","name":"power","translatesPath":"/assets/i18n/power","type":"ts"}],"type":"com.fibaro.FGR223","baseType":"com.fibaro.FGR","enabled":true,"visible":true,"isPlugin":false,"parentId":451,"viewXml":false,"hasUIView":true,"configXml":false,"interfaces":["calibratable","energy","favoritePosition","notification","parameters","power","resetMeter","zwave","zwaveProtection","zwaveResources"],"properties":{"parameters":[],"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,6,2","zwaveVersion":"5.1","RFProtectionState":0,"RFProtectionSupport":3,"calibrated":true,"calibrationVariants":["rollerShutterCalibration"],"categories":["gates"],"configured":true,"dead":false,"deadReason":"","deviceControlType":57,"deviceIcon":49,"deviceRole":"GateWithPositioning","endPointId":1,"energy":1.05,"favoritePositions":[{"label":"Favorite position 1","name":"favoritePosition1","value":50}],"favoritePositionsNativeSupport":false,"icon":{"path":"/assets/icon/fibaro/garaz/garaz0.png","source":"HC"},"includeInEnergyPanel":true,"localProtectionState":0,"localProtectionSupport":5,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"model":"","nodeId":67,"parameterProvider":"zwave","parametersTemplate":"822","power":0.6000000000000001,"productInfo":"1,15,3,3,16,0,5,1","protectionExclusiveControl":0,"protectionExclusiveControlSupport":false,"protectionState":0,"protectionTimeout":0,"protectionTimeoutSupport":false,"saveLogs":true,"saveToEnergyPanel":true,"serialNumber":"","showEnergy":true,"state":"Unknown","storeEnergyData":true,"supportedDeviceRoles":["BlindsWithPositioning","VenetianBlinds","GateWithoutPositioning","GateWithPositioning","BlindsWithDriver","BlindsWithDriverImpulse"],"supportedNotifications":{"8":{"eventValues":{},"key":"blockScenes.notification.properties.8","stateValues":{"over-current-status":{"key":"blockScenes.notification.properties.over-current-status","values":{"0":{"key":"blockScenes.notification.properties.8.0","saveToPanel":true},"6":{"key":"blockScenes.notification.properties.8.6","saveToPanel":true}}}}},"9":{"eventValues":{},"key":"blockScenes.notification.properties.9","stateValues":{"hw-status":{"key":"blockScenes.notification.properties.hw-status","values":{"0":{"key":"blockScenes.notification.properties.9.0","saveToPanel":true},"3":{"key":"blockScenes.notification.properties.9.3","saveToPanel":true}}}}}},"useTemplate":true,"userDescription":"","value":0,"value2":99,"zwaveResources":[{"name":"Meter","rateType":1,"scales":[0],"type":1},{"name":"Meter","rateType":1,"scales":[2],"type":1}]},"actions":{"close":0,"open":0,"reconfigure":0,"reset":0,"setFavoritePosition":1,"setValue":1,"setValue2":1,"startCalibration":1,"stop":0},"created":1692536704,"modified":1699462779,"sortOrder":222}

**Comment by mkz212** [comment]
@RikBast 

Thank you for taking the time and sending the API response. I have already added PR with a correction. We are waiting for @ilcato to include it and release an update. From what I see it will be displayed as a garage door. 

If you can write also:
- as what the device is set (Fibaro panel, Role field for this device)?
- what HC you have (hc2, hc3 etc.) and what firmware version?

**Comment by RikBast** [comment]
It's role is 'gate with positioning' and I have HC3 v5.150

**Comment by mkz212** [comment]
Should be fixed in 1.5.0 beta 5.
