### ISSUE TITLE
Aeotec wallmote

### ISSUE THREAD

**Issue by jurassiksame** [ilcato/homebridge-fibaro-home-center#181]
Hi @mkz212  and @ilcato why the thread was closed before finish before ti send the information requested ?

@mkz212 

its all the information you need:

Device kind: Remote Controller

"id":1142,"name":"Interruptor","roomID":233,"type":"com.fibaro.remoteController","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":0,"remoteGatewayId":5,"viewXml":false,"configXml":false,"remoteGatewayId":5,"interfaces":["battery","fibaroFirmwareUpdate","remoteGateway","zwave","zwaveAlarm","zwaveCentralScene","zwaveMultiChannelAssociation","zwaveWakeup"],"properties":{"alarmLevel":"0","alarmType":"0","batteryLevel":"255","batteryLowNotification":"true","categories":"[\"remotes\"]","centralSceneSupport":"[{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":1},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":2},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":3},{\"keyAttributes\":[\"Pressed\",\"Released\",\"HeldDown\"],\"keyId\":4}]","configured":true,"dead":"false","deadReason":"","defInterval":"0","deviceControlType":"0","deviceIcon":"103","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","firmwareUpdate":"{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"2.3\"}","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","nodeId":"27","parameters":[],"parametersTemplate":"0","pollingTimeSec":0,"productInfo":"0,134,0,2,0,130,2,3","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","updateVersion":"","useTemplate":"false","userDescription":"","wakeUpTime":0,"zwaveCompany":"AEON Labs","zwaveInfo":"3,4,62","zwaveVersion":"2.3"},"actions":{"abortUpdate":1,"reconfigure":0,"retryUpdate":1,"setInterval":1,"startUpdate":1,"updateFirmware":1},"created":1699213060,"modified":1699213060,"sortOrder":650},{"id":1143,"name":"Sensor 

Regards

**Comment by mkz212** [comment]
@jurassiksame 

I don't know why the post was closed (probably by mistake or sometimes it happens automatically).

That's what API is about. Thanks.

**Comment by jurassiksame** [comment]
Hi @mkz212 

I been thinking what you said, and you are right, why I need to add the switches if I could control the lights or other stuff directly….
So I think don’t make sense to add it.

but it works like you said.

so I think this thread could be closed.

very thanks

**Comment by mkz212** [comment]
@jurassiksame 

I am glad that I helped and we understand each other. 

As a curiosity, I will say that below you have a "Close issue" button.
