### ISSUE TITLE
Flush Dimmer 0-10V

### ISSUE THREAD

**Issue by jurassiksame** [ilcato/homebridge-fibaro-home-center#182]
Hi Guys why the Quoin Flush dimmer on HomeKit only have function to on-off if in hc2 we can dimmer this module ?

Regards

Very thanks

**Comment by jurassiksame** [comment]
On Hc2:
<img width="753" alt="Captura de ecrã 2023-11-15, às 22 04 54" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/149274289/a3a9d48e-d409-4360-a7f5-1dacaa7a3034">

on homekit:
<img width="689" alt="Captura de ecrã 2023-11-15, às 22 05 48" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/149274289/97b72fd8-e69c-4ef7-913f-5c618ef10dd8">

**Comment by mkz212** [comment]
@jurassiksame Please attach API response for this device.

**Comment by mkz212** [comment]
@jurassiksame ?

**Comment by jurassiksame** [comment]
Hi @mkz212 

sorry for delays, quite busy here, really sorry.

API:

{"id":1147,"name":"VMC","roomID":234,"type":"com.fibaro.multilevelSwitch","baseType":"com.fibaro.binarySwitch","enabled":true,"visible":true,"isPlugin":false,"parentId":0,"remoteGatewayId":5,"viewXml":false,"configXml":false,"remoteGatewayId":5,"interfaces":["deviceGrouping","levelChange","remoteGateway","zwave","zwaveMultiChannelAssociation","zwaveSwitchAll"],"properties":{"categories":"[\"ambience\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"1","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"15","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","log":"transfer OK","logTemp":"TxtGreen","manufacturer":"","markAsDead":"true","model":"","nodeId":"10","parameters":[],"parametersTemplate":"0","pollingTimeSec":0,"productInfo":"1,89,0,1,0,83,1,1","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"ZMNHVD1 H1S1P1","smsNotificationID":"0","smsNotificationType":"0","switchAllMode":"","useTemplate":"false","userDescription":"","value":"95","zwaveCompany":"Goap","zwaveInfo":"3,4,5","zwaveVersion":"1.1"},"actions":{"reconfigure":0,"setValue":1,"startLevelDecrease":0,"startLevelIncrease":0,"stopLevelChange":0,"turnOff":0,"turnOn":0},"created":1699213060,"modified":1699213060,"sortOrder":655}

You mean : controlled device: 2other device" its this ?

Very thanks

**Comment by mkz212** [comment]
@jurassiksame Also please open Fibaro administration panel, then open your device (as on screenshots you post) , then open Advanced tab and check field "This device cotrols...." (or something similar)- how it is set?

**Comment by jurassiksame** [comment]
Hi @mkz212 

its like the print screen you send.

**Comment by mkz212** [comment]
@jurassiksame Can You try set this as Light?

**Comment by jurassiksame** [comment]
@mkz212  yes I can do no problem, it will fix ?

Regards

**Comment by mkz212** [comment]
@jurassiksame it should. But check first troubleshooting section on plugin homepage.

**Comment by jurassiksame** [comment]
Hi @mkz212 it works perfectly you are the best.


So this means if the device in fibaro home center not set correctly in “ controlled device” the device could be exposed with not all features?


Regards

**Comment by mkz212** [comment]
@jurassiksame Only for some devices, the role field selection matters. More informations you will find in Troubleshooting section on the plugin page. If the problem is solved, please close Issue.
