### ISSUE TITLE
Plugin icon

### ISSUE THREAD

**Issue by mkz212** [ilcato/homebridge-fibaro-home-center#193]
@ilcato 

Now you can add plugin icon. Admin of the plugin must fill this form: 

https://github.com/homebridge/verified/issues/new?assignees=&labels=&projects=&template=icon-request.yml&title=Plugin+Icon+Request

My icon suggestion for this plugin:
![homebridge-fibaro-home-center](https://github.com/ilcato/homebridge-fibaro-home-center/assets/82271669/f9ed50f8-42d1-4344-9389-23816fa1cada)

[homebridge-fibaro-home-center.zip](https://github.com/ilcato/homebridge-fibaro-home-center/files/13700126/homebridge-fibaro-home-center.zip)

**Comment by mkz212** [comment]
@ilcato Please take a look. It's a simple step to add this logo and I think it's worth it.

**Comment by ilcato** [comment]
done

**Comment by mkz212** [comment]
👍
