### ISSUE TITLE
"com.fibaro.multilevelSwitch" incorrectly displays in HomeKit App

### ISSUE THREAD

**Issue by vkamenski** [ilcato/homebridge-fibaro-home-center#20]
A device with the type of "com.fibaro.multilevelSwitch" incorrectly displays in HomeKit App. It should have a slicer control instead of binary "on" and "off".

Fibaro HC3. I can increase or decrease the fan by changing the brightness control.
![HC3](https://user-images.githubusercontent.com/607015/104852346-a30d4400-590b-11eb-9ae2-3c2d74a5549b.JPG)

iOS HomeKit App. Only on and off states are there.
![iOS HomeKit App](https://user-images.githubusercontent.com/607015/104852420-0303ea80-590c-11eb-8177-7de54820720b.jpg)

**Comment by ilcato** [comment]
@vkamenski can you show me the General and Advanced tab in home center for this device?

**Comment by vkamenski** [comment]
![Capture1](https://user-images.githubusercontent.com/607015/113623830-91644e80-9667-11eb-80c8-eb9e2179886e.JPG)
![Capture](https://user-images.githubusercontent.com/607015/113623843-945f3f00-9667-11eb-8c4e-043f24edcc22.JPG)

**Comment by ilcato** [comment]
@vkamenski can you send me the json object of the device rest api?

**Comment by mkz212** [comment]
Dimmer 2 (com.fibaro.FGD212) also is displayed as on/off. It should have a slicer control.

**Comment by mkz212** [comment]
"type":"com.fibaro.FGD212",
"baseType":"com.fibaro.multilevelSwitch",

**Comment by ilcato** [comment]
@mkz212 what's the value of `deviceControlType` ?

**Comment by mkz212** [comment]
23

**Comment by ilcato** [comment]
@mkz212 is it formatted as a string or as a number ?

**Comment by mkz212** [comment]
String. "deviceControlType":"23"

**Comment by ilcato** [comment]
ok, that's the problem. Will fix it.

**Comment by ilcato** [comment]
@vkamenski @mkz212 can you test version 1.1.17 ?

**Comment by mkz212** [comment]
Now kind of works. But I had to clean the cache. 

The worst thing is that when I move the slider, the light blinks. For example, when I do from 2% to 100% it should only lighten up but it makes it brighter, darker, brighter. 

And sometimes he doesn't listen. I change the value, the slider goes up and then goes back to the old position.

**Comment by mkz212** [comment]
handling with scenes also has problems. I did two scenes. one set the light to 80%, the other set to 5% and the same flashes and jamming light as if it only reacted after a while.

**Comment by ilcato** [comment]
@mkz212, please open different issues for those problems (it seems that they are related to a bug in Home Center on the refreshState, investigating). Closing this one.
