### ISSUE TITLE
Hope to add the fan function of the air conditioner

### ISSUE THREAD

**Issue by baduxiyang** [ilcato/homebridge-fibaro-home-center#252]
Hope to add the fan function of the air conditioner

**Comment by mkz212** [comment]
@baduxiyang 

Please explain it a little more thoroughly. 

However, you must know that HomeKit and Apple limit the possibilities of how AC should look in their system. The point is that as a mode it is: Auto, cooling, heating, off. In addition, there is one Oscilate switch (usually used for swing mode). In addition, there is a Rotation speed slider. These elements cannot be changed.

How do you imagine adding Fan mode? And do you mean a mode like heating and cooling?

**Comment by baduxiyang** [comment]
@mkz212 
This is a function displayed on the device!
![20240107124950](https://github.com/ilcato/homebridge-fibaro-home-center/assets/53244835/c8aa773b-0477-4fb0-a8f9-76ad6fc9424e)

**Comment by mkz212** [comment]
So you mean Climate / Heating zone? And fan speed?

**Comment by mkz212** [comment]
@baduxiyang Please write the name of the plugin you are using for AC. And show please how this device is displayed in HomeKit? Do you have a Rotation speed slider there?

**Comment by mkz212** [comment]
@ilcato 

I think that this should be Heater Cooler instead of Thermostat. https://developers.homebridge.io/#/service/HeaterCooler

Here it will display Rotation speed slider and Oscilate Switch.

**Comment by baduxiyang** [comment]
yes

**Comment by ilcato** [comment]
But there's no fan controls in Climate / Heating zones

**Comment by mkz212** [comment]
> But there's no fan controls in Climate / Heating zones

Maybe it's some kind of plugin to operate the air conditioning?
