### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by tombudowniczy** [ilcato/homebridge-fibaro-home-center#259]
Hello, I have a configuration problem on HC2, the plugin doesn’t work. I’m getting this message
[05/01/2024, 20:54:53] [FibaroHC] Error getting data from Home Center:  Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  response: undefined
}
[05/01/2024, 20:54:53] [FibaroHC] Next try in 5 minutes

**Comment by mkz212** [comment]
@tombudowniczy 

- Do you have latest plugin version? 1.7.0?
- In field 'URL or IP' what do you enter?

**Comment by tombudowniczy** [comment]
Tak, mam 1.7.0
IP
Yes, the IP I am providing is correct. I have also checked the login and password several times. I tried inserting different ones, but nothing works

**Comment by mkz212** [comment]
So if you open the exact same IP address in the browser that you provided, the login page opens? And if you provide a username and password such as you provided in the settings, will you log in? And you have access to devices, etc.?

**Comment by tombudowniczy** [comment]
Yes, logging in using the IP address and using that information works correctly

**Comment by ilcato** [comment]
> Yes, logging in using the IP address and using that information works correctly

From the same machine that runs homebridge?

**Comment by tombudowniczy** [comment]
Homebridge worked with a different Fibaro plugin, so I assume there is no issue with logging in from the device level. Unless you mean a different login method?

**Comment by tombudowniczy** [comment]
I don't understand the step: (put ca.cer file in the same folder as config.json). Besides the installation, should I manually add any files?

**Comment by mkz212** [comment]
@tombudowniczy

Enter exactly what you have entered in the URL / IP field. If it starts with https (not http) then you need to put a ca file. You will generate this file in HC.

**Comment by ilcato** [comment]
the ca.cer file is neccessary if you are using https.
if you put in the url field the ip address it is not necessary.
But the https maybe mandatory if you configured the home center requiring it.

**Comment by mkz212** [comment]
You have 3 options: 
- 192.168.1.100
- https://hc-00000XXX.local (put ca.cer file in the same folder as config.json)
- http://hc-00000XXX.local

These are only examples. Replace with your address.

**Comment by tombudowniczy** [comment]
I log into the central unit without using HTTP, so that probably isn't the issue

**Comment by mkz212** [comment]
> I log into the central unit without using HTTP, so that probably isn't the issue

Enter what you have typed in the URL / IP field.

**Comment by tombudowniczy** [comment]
I provided the IP address of my Home Center 2: 192.168.1.186

**Comment by ilcato** [comment]
So you are not using https and the ca.cer file is irrelevant.

**Comment by ilcato** [comment]
> Homebridge worked with a different Fibaro plugin, so I assume there is no issue with logging in from the device level. Unless you mean a different login method?

Which other plugin are you talking about?

**Comment by tombudowniczy** [comment]
https://github.com/ilcato/homebridge-Fibaro-HC2

**Comment by ilcato** [comment]
which version of homebridge are you using? Try to adopt the latest version with the latest nodejs environment. Are you on docker?

**Comment by tombudowniczy** [comment]
I have just updated to version node.js v18.19.0 still not working
 [09/01/2024, 23:33:51] [FibaroHC] Error getting data from Home Center:  Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  response: undefined
}
[09/01/2024, 23:33:51] [FibaroHC] Next try in 5 minutes

**Comment by ilcato** [comment]
which version of homebridge are you using? Are you on docker?

**Comment by tombudowniczy** [comment]
homebridge v1.7.0 on node.js v18.19.0 
sorry I don't underspent what is a docker?

**Comment by tombudowniczy** [comment]
understand

**Comment by tombudowniczy** [comment]
Could the issue be that Homebridge is on 192.168.0.*** while HC2 is on 192.168.1.***?

**Comment by mkz212** [comment]
> Could the issue be that Homebridge is on 192.168.0.*** while HC2 is on 192.168.1.***?

Other plugin works for you with this configuration? Where HC is not in the same local network as Homebridge (not in the same IP address range)?

**Comment by tombudowniczy** [comment]
So, other plugins were working this way. However, this one didn't want to. I had a problem changing the IP address on Homebridge, and I still don't know how to do it. However, I changed the DHCP settings, and now the addresses are static and in the same subnet, which solved the problem. If someone could suggest how to set static IP on Homebridge so I know for the future, I would be grateful. Thanks for the help

**Comment by mkz212** [comment]
I'm not sure if they have to be in the same subnet (the same address pool). I thought so. Even on the official Fibaro website I found information that yes - they must be in the same subnet. But @ilcato tested and managed to connect from another subnet - maybe it depends on the router settings?

Regarding the static IP setting:
- you can assign IP to MAC in the router settings (main router with dhcp enabled). 
- You can set a fixed IP in Fibaro Home Center / Yubii Home
- You can assign a fixed IP for Homebridge. I don't know how to do it for Synology, but for Raspberry Pi: open the terminal, type 'sudo raspi-config', there you choose network options and set it.

**Comment by tombudowniczy** [comment]
Okay, thanks for the help. I consider the topic closed. In summary, it's best if the IP addresses of both devices are in the same subnet.
