### ISSUE TITLE
al sensors missed

### ISSUE THREAD

**Issue by Uzzus** [ilcato/homebridge-fibaro-home-center#264]
After the last update from the Home app, all contact motion and smoke sensors disappeared.
Home bridge on the devices page, however, they are all present. Is there perhaps some parameter to be configured for Apple Home to show them?
My system consists of Synoilogy nas in which I installed the standalone homebridge package and the Fibaro Home Center homebridge plugin, Node.js 20.
Log show this error: [Homebridge UI] Could not check glibc version: Command failed: getconf GNU_LIBC_VERSION 2>/dev/null

Thanks

**Comment by ilcato** [comment]
@Uzzus which version of homebridge are you using?

**Comment by Uzzus** [comment]
> @Uzzus which version of homebridge are you using?

3.1.1

**Comment by mkz212** [comment]
> > @Uzzus which version of homebridge are you using?
> 
> 3.1.1

Newest public version of Homebridge is 1.7.0

**Comment by Uzzus** [comment]
> @Uzzus
> 
>     * none of the latest plugin updates changed anything about the mentioned devices.
> 
>     * As for the error you indicate, you have to write on the Homebridge UI forum, I know that there has been a lot of confusion in connection with GLIBC recently.
> 
>     * write more about your configuration: what version of homebridge, homebridge ui, node, iOS, etc.

Homebridge 3.1.1 Node 20 Homebridge 1.7.0 ios 17.2.1

**Comment by mkz212** [comment]
If there is problem with device you can go to Homebridge settings and remove one or more devices from cache.

**Comment by Uzzus** [comment]
the strange thing is that on the homebridge devices page they are all present

**Comment by ilcato** [comment]
> After the last update from the Home app, all contact motion and smoke sensors disappeared.

What do you mean with `update from the Home app` ?

**Comment by Uzzus** [comment]
> > After the last update from the Home app, all contact motion and smoke sensors disappeared.
> 
> What do you mean with `update from the Home app` ?

sorry my english suks i mean in the apple Home disappears

**Comment by Uzzus** [comment]
> > the strange thing is that on the homebridge devices page they are all present
> 
> If it is displayed in homebridge, the problem is not on the plugin side. Therefore, I propose to remove from the cache and it should appear.

in the afternoon I'll try thanks

**Comment by mkz212** [comment]
@Uzzus Let us know if it helped and solved problem.

**Comment by Uzzus** [comment]
> @Uzzus Let us know if it helped and solved problem.
Solved.
At first i tried to remove some devices from the cache but it didn't detect them, then I tried to delete the entire cache but nothing changed, at the end I solved by deleting my house from the Home app and adding homebridge to the Home app again, so I think it's a problem with the latest Apple updates. Thanks anyway for the technical support.

**Comment by mkz212** [comment]
@Uzzus 

Unfortunately, even Apple makes mistakes. I'm sorry you had to set everything up again. Unfortunately, Homebridge and HomeKit is not an official cooperation, so we are still happy that it works.

If the problem is solved then please close Issue.
