### ISSUE TITLE
Global variables dimmers what should de values be in Fibaro

### ISSUE THREAD

**Issue by hcoppen** [ilcato/homebridge-fibaro-home-center#265]
Hi,

I can't find any documentatie about the predefined values that the global variable for dimmers should have in Fibaro. I tried 0 - 100 with steps of 10 but that didn't work.

**Comment by hcoppen** [comment]
My normal switch isn't working anymore I get an error. Does this get something to do with change in url settings? I do hame admin username and password in config file. And just my IP in the url

Error fetching updates:  TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Poller.manageGlobalVariableDevice (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:166:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Poller.poll (/var/lib/homebridge/node_modules/homebridge-fibaro-home-center/src/pollerupdate.ts:63:7)

**Comment by mkz212** [comment]
@hcoppen Check Manuals section in main page (readme). There you can find that for global variables it is created switch with only true / false value.

**Comment by hcoppen** [comment]
The switch was working with true / false till I reinstalled 1.7.1 on child bridge. Now it gives error see above

**Comment by ilcato** [comment]
@hcoppen, problem is fixed in 1.7.2-beta.0, please have a try.
Range for dimmers global variables is 0-100. Will update docs.
Thanks

**Comment by ilcato** [comment]
ok, closing  issue
