### ISSUE TITLE
does the plugin work with Yubii? - for the Elero shutters

### ISSUE THREAD

**Issue by meydo1** [ilcato/homebridge-fibaro-home-center#292]
does the homebridge plugin work with Yubii to manage the Elero shutters?

**Comment by ilcato** [comment]
It should. But I do not have that devices. Please try it.

**Comment by meydo1** [comment]
and is it also possible with this one?
https://www.elero.de/de/produkte/steuerungen/centero-home/
Centero Home NXT

**Comment by ilcato** [comment]
don't know
