### ISSUE TITLE
Smart Implant switches missing

### ISSUE THREAD

**Issue by tzalexander** [ilcato/homebridge-fibaro-home-center#297]
the temperature sensors of the smart implants are shown (added) to the devices list in homebridge but the potential free switches of the same device are not displayed in homebridge and homekit

**Comment by mkz212** [comment]
@ilcato The smart implant has a built-in temperature sensor but in my experience it does not work very well and is not very accurate. Personally, I wouldn't want it to be added. So if you decide to add it, please do it as an option in the plugin config.

**Comment by tzalexander** [comment]
@ilcato sure:
{"id":849,"name":"Tortaster","roomID":11,"type":"com.fibaro.binarySwitch","baseType":"com.fibaro.actor","enabled":true,"visible":false,"isPlugin":false,"parentId":841,"remoteGatewayId":0,"interfaces":["deviceGrouping","zwave","zwaveProtection"],"properties":{"parameters":[{"id":24,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":25,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":40,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":41,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":47,"lastReportedValue":255,"lastSetValue":255,"size":2,"value":255},{"id":49,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":52,"lastReportedValue":255,"lastSetValue":255,"size":2,"value":255},{"id":54,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":63,"lastReportedValue":5,"lastSetValue":5,"size":1,"value":5},{"id":64,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":65,"lastReportedValue":5,"lastSetValue":5,"size":2,"value":5},{"id":66,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":67,"lastReportedValue":5,"lastSetValue":5,"size":2,"value":5},{"id":68,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":150,"lastReportedValue":10,"lastSetValue":10,"size":1,"value":10},{"id":151,"lastReportedValue":10,"lastSetValue":10,"size":1,"value":10},{"id":152,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":153,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":154,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":155,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":156,"lastReportedValue":5,"lastSetValue":5,"size":2,"value":5},{"id":157,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":21,"lastReportedValue":3,"lastSetValue":3,"size":1,"value":3}],"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,6,2","zwaveVersion":"5.2","RFProtectionState":"0","RFProtectionSupport":"3","categories":"[\"other\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"20","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"2","emailNotificationID":"0","emailNotificationType":"0","endPointId":"5","localProtectionState":"0","localProtectionSupport":"5","log":"","logTemp":"","manufacturer":"","markAsDead":"false","model":"","nodeId":"158","parametersTemplate":"825","productInfo":"1,15,5,2,16,0,5,2","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000007561","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"reconfigure":0,"turnOff":0,"turnOn":0},"created":1707507704,"modified":1707507704,"sortOrder":392}

fyi:
Recently (after setup) i have changed the flag "markAsDead" from true to false - maybe devices are ignored which are marked as dead? If yes - shouldn't it have been added after homebridge restart?

thank you

**Comment by ilcato** [comment]
@tzalexander , `com.fibaro.binarySwitch` should be selected accordingly to the advance control in the [documentation](https://github.com/ilcato/homebridge-fibaro-home-center/blob/main/docs/advcontrol.md).

**Comment by mkz212** [comment]
@tzalexander Field Role is in Fibaro web panel, in this device settings.

**Comment by tzalexander** [comment]
@mkz212 thank you. Unfortunately, it's still not clear to me which input field this should be - I am using the panel in a different language.

Could it be that the “controlled module” field is meant? (see screenshot)

<img width="769" alt="Bildschirmfoto 2024-02-14 um 09 26 15" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/47521268/0ab6d328-5e10-4032-93c7-7f0c262b660d">

**Comment by mkz212** [comment]
> @mkz212 thank you. Unfortunately, it's still not clear to me which input field this should be - I am using the panel in a different language.
> 
> Could it be that the “controlled module” field is meant? (see screenshot)
> 
> <img alt="Bildschirmfoto 2024-02-14 um 09 26 15" width="769" src="https://private-user-images.githubusercontent.com/47521268/304668647-0ab6d328-5e10-4032-93c7-7f0c262b660d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTk3MTksIm5iZiI6MTcwNzg5OTQxOSwicGF0aCI6Ii80NzUyMTI2OC8zMDQ2Njg2NDctMGFiNmQzMjgtNWUxMC00MDMyLTkzYzctN2YwYzI2MmI2NjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA4MzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGZkNTUxMzgyNTIxN2RhMDU2MDEwMzVhYjkwNTJkZWFlNmRlMGY3ZDMyYmY1NGFkYTA2NmQzNmExMzRjMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wM7WHrG7gBBpIsaJC1wWcGpbTN4hHqGcFAM5kwHbp-8">

Yes.

**Comment by tzalexander** [comment]
@mkz212 thank you very much.

Just for the sake of completeness @ilcato :
The option "other" is currently selected as role in the device settings. According to the documentation, this should show up as a switch in HomeKit - which it doesn't.

<img width="1099" alt="Bildschirmfoto 2024-02-14 um 09 42 49" src="https://github.com/ilcato/homebridge-fibaro-home-center/assets/47521268/1d96e77f-60ec-40d8-8d15-194ed25cc53c">

**Comment by tzalexander** [comment]
@mkz212 fyi: the change of the role (and the restart of homebridge) does not affect anything - unfortunately the module is still missing. Best

**Comment by ilcato** [comment]
@tzalexander, can you share the config file (without secrets) ?

**Comment by tzalexander** [comment]
@ilcato sure

{
    "name": "FibaroHC2",
    "url": "192.168.1.20",
    "username": "theUsername",
    "password": "thePWD",
    "pollerperiod": 3,
    "thermostattimeout": 7200,
    "thermostatmaxtemperature": 100,
    "switchglobalvariables": "hb_sw_garage",
    "adminUsername": "theAdminUsername",
    "adminPassword": "theAdminPWD",
    "securitysystem": "disabled",
    "addRoomNameToDeviceName": "disabled",
    "logsLevel": 1,
    "advControl": 1,
    "platform": "FibaroHC"
}

**Comment by ilcato** [comment]
@tzalexander,
any strange message in the log?
is the device present in the homebridge UI in the Accessories tab?

**Comment by tzalexander** [comment]
@ilcato 
the only "not normal" message is:
[15/02/2024, 17:49:48] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

I don't think that this has something to do with the missing devices.

The two missing switches (both from smart implant) are missing in the Accessories tab also.
The temperatures from that same smart implant are shown in the list.

**Comment by tzalexander** [comment]
@ilcato both switches are hidden from the normal modules list in the admin panel (setting: "device will not be shown in system") – could that be the problem?

**Comment by tzalexander** [comment]
@ilcato YES - this was the problem. thank you for your help – the device has to be visible in the fibaro admin panel module standard view.

**Comment by tzalexander** [comment]
@ilcato may i ask you a second question in here?
I have created another heating section with a vertiual device after the homebridge fibaro plugin setup and I don't get it into the Accessories list. How do I get a new heating control section into that list? Thank you very much

**Comment by ilcato** [comment]
@tzalexander, are you saying that other heating zones appear on homebridge but not the new one?

**Comment by tzalexander** [comment]
@ilcato yes

**Comment by ilcato** [comment]
> @ilcato yes

Did you restart homebridge?

**Comment by tzalexander** [comment]
@ilcato yes - multiple times

**Comment by ilcato** [comment]
@tzalexander, can you close this issue and open a new specific one?
