### ISSUE TITLE
new heating zones missing

### ISSUE THREAD

**Issue by tzalexander** [ilcato/homebridge-fibaro-home-center#309]
I have created a new heating section after the homebridge fibaro plugin setup.
I don't get it into the accessories list.
How do I get a new heating control section into that list?
Thank you

**Comment by tzalexander** [comment]
@ilcato I am using HC2

**Comment by ilcato** [comment]
@tzalexander can you try to call the '/api/panels/heating' API and see if all the heating zones are returned?

**Comment by tzalexander** [comment]
@ilcato is it possible that the heating ids somehow collides with device ids?

**Comment by ilcato** [comment]
@tzalexander interesting

**Comment by ilcato** [comment]
@tzalexander do you have such a collision in your setup?

**Comment by ilcato** [comment]
@tzalexander can you test 1.7.4-beta.2 ?

**Comment by tzalexander** [comment]
@ilcato collision?
I checked all heating zone IDs in

**Comment by ilcato** [comment]
@tzalexander remove from the cache all heating zone related accessories.

**Comment by ilcato** [comment]
@tzalexander try beta 3

**Comment by tzalexander** [comment]
@ilcato the update to beta 3 worked fine. all heating zones are listed in the accessories list now. thank you
