### ISSUE TITLE
Can I just use this plugin for the security alarm?

### ISSUE THREAD

**Issue by richardmarr** [ilcato/homebridge-fibaro-home-center#318]
Not sure - but just want to use this plugin for the security alarm function only to start with… not lights etc 

is this possible?

**Comment by ilcato** [comment]
@richardmarr, yes you can configure only this aspect. You MUST use a home center user with no visibility on the devices you want to exclude.

**Comment by richardmarr** [comment]
Thanks… really appreciate this…

What would this be if I just want this plugin to arm, disarm, night alarm etc?

I have a couple of sirens… lights that turn on etc when the alarm is breached… but this user would not need access to those?

**Comment by ilcato** [comment]
@richardmarr exactly, you MUST code the activation of sirens and lights in your scripts.

**Comment by richardmarr** [comment]
Does the user need to be an admin user even though they may have very limited access per the above thread?

**Comment by richardmarr** [comment]
Will do..

can you set the device variables in a block scene… couldn’t see how? Eg Fibaro.alarm

**Comment by richardmarr** [comment]
Dont worry... I used a block scene and just disarmed the whole house and rearmed the zone using a block rather than device variable - thanks!!!
