### ISSUE TITLE
Sometimes alarm shows no response and I can’t turn the alarm off until it responds

### ISSUE THREAD

**Issue by richardmarr** [ilcato/homebridge-fibaro-home-center#334]

**Comment by richardmarr** [comment]
Sometimes alarm shows no response and I can’t turn the alarm off until it responds

![IMG_5136](https://github.com/ilcato/homebridge-fibaro-home-center/assets/26127892/485419e9-29a8-4090-83a9-555f12164730)

**Comment by richardmarr** [comment]
Help?

**Comment by ilcato** [comment]
@richardmarr can fully describe the scenario? Can you share the log?
