### ISSUE TITLE
The news roll control from nice doesn´t appear

### ISSUE THREAD

**Issue by Kimbosmart** [ilcato/homebridge-fibaro-home-center#373]
I have a fibaro HC3 conected with a hoobs and i installed the new roll control of nice, when i finished the instalation they doesn´t appear in my Home application.

What can i do to got it?

Thank you very much in advance

**Comment by mkz212** [comment]
@Kimbosmart 

Not all devices are currently supported. I added two PR to fix it. Paste here response API for this device (how to get response you can check in this plugin readme). 

@ilcato  Any chance you'll take a look at my PRs?

**Comment by Kimbosmart** [comment]
@mkz212 Here you have the device API responses
[drive-download-20240604T084045Z-001.zip](https://github.com/user-attachments/files/15545376/drive-download-20240604T084045Z-001.zip)

**Comment by Kimbosmart** [comment]
Hello, those were the responses from five "_NICE_  Roll-control" , and it should be showing in the HOOBS Box control panel as a blind/curtain control

**Comment by mkz212** [comment]
@Kimbosmart I don't think you pasted the response. Anyway, I don't see.

**Comment by Kimbosmart** [comment]
When I paste this in the browser with the IP of the HC and the ID´s from the devices, the browser show:

{"id":96,"name":"Persiana dormitorio Andrea","roomID":229,"view":
[{"assetsPath":"dynamicplugins/com.fibaro.rollerShutter","name":"com.fibaro.rollerShutter","translatesPa
th":"/assets/i18n/com.fibaro.rollerShutter","type":"ts"},{"assetsPath":"dynamicplugins/energy","name":"energy","translatesPath":"/assets/i18n/energy","type":"ts
"},{"assetsPath":"dynamic-plugins/favorite-positions","name":"favoritepositions","translatesPath":"/assets/i18n/favorite-positions","type":"ts"},
{"assetsPath":"","name":"level-change","translatesPath":"/assets/i18n/levelchange","type":"ts"}],"type":"com.fibaro.FGR224","baseType":"com.fibaro.FGR","ena
bled":true,"visible":true,"isPlugin":false,"parentId":95,"viewXml":false,"hasUIVi
ew":true,"configXml":false,"interfaces":
["calibratable","energy","favoritePosition","fibaroFirmwareUpdate","levelChange",
"zwave","zwaveAlarm","zwaveIndicator","zwaveMultiChannelAssociation","zwaveProtec
tion"],"properties":{"parameters":
[{"id":20,"lastReportedValue":3,"lastSetValue":3,"size":1,"value":3},
{"id":24,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},
{"id":25,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},
{"id":40,"lastReportedValue":15,"lastSetValue":15,"size":1,"value":15},
{"id":41,"lastReportedValue":15,"lastSetValue":15,"size":1,"value":15},
{"id":150,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},
{"id":151,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},
{"id":152,"lastReportedValue":15,"lastSetValue":15,"size":2,"value":15},
{"id":156,"lastReportedValue":159,"lastSetValue":159,"size":2,"value":159},
{"id":157,"lastReportedValue":157,"lastSetValue":157,"size":2,"value":157},
{"id":158,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},
{"id":159,"lastReportedValue":50,"lastSetValue":50,"size":1,"value":50},
{"id":160,"lastReportedValue":50,"lastSetValue":50,"size":1,"value":50}],"polling
TimeSec":0,"zwaveCompany":"NICE","zwaveInfo":"3,7,18","zwaveVersion":"8.1","RFPro
tectionState":0,"RFProtectionSupport":3,"alarmLevel":0,"alarmType":0,"buttonsType
":"doubleBiStable","calculatedState":"Opened","calibrated":true,"calibrationVaria
nts":["rollerShutterCalibration"],"categories":
["blinds"],"configured":true,"dead":false,"deadReason":"","deviceControlType":54,
"deviceIcon":20,"deviceRole":"BlindsWithPositioning","endPointId":0,"energy":0.0,
"favoritePositions":[{"label":"Favorite
position","name":"FavoritePosition1","value":50}],"favoritePositionsNativeSupport
":true,"firmwareUpdate":
{"info":"","progress":0,"status":"UpToDate","updateVersion":"8.1"},"icon":
{"path":"/assets/icon/fibaro/roleta/roleta40.png","source":"HC"},"indicatorSuppor
tedProperties":[],"indicatorValue":[{"id":0,"properties":
{"0":0}}],"localProtectionState":0,"localProtectionSupport":5,"log":"","logTemp":
"","manufacturer":"","markAsDead":true,"model":"","motorInversion":true,"movingDo
wnTime":15700,"movingUpTime":15900,"nodeId":17,"parametersTemplate":"967","produc
tInfo":"1,15,3,4,16,0,8,1","protectionExclusiveControl":0,"protectionExclusiveCon
trolSupport":false,"protectionState":0,"protectionTimeout":0,"protectionTimeoutSu
pport":false,"saveLogs":true,"saveToEnergyPanel":true,"serialNumber":"h'000000000
04c563c","slatsRange":0,"slatsRotationTime":1500,"state":"Unknown","steeringInver
sion":true,"storeEnergyData":true,"supportedDeviceRoles":
["BlindsWithPositioning","Awning","Curtain","Pergola","VenetianBlinds"],"targetVa
lue":39,"updateVersion":"","useTemplate":true,"userDescription":"","value":39,"va
lue2":0,"virtualBottomLimit":0},"actions":
{"abortUpdate":1,"close":0,"configureFavoritePositions":1,"open":0,"reconfigure":
0,"reset":0,"retryUpdate":1,"setFavoritePosition":1,"setIndicatorValue":1,"setVal
ue":1,"setValue2":1,"startCalibration":1,"startLevelDecrease":0,"startLevelIncrea
se":0,"startUpdate":1,"stop":0,"stopLevelChange":0,"updateFirmware":1},"created":
1716888802,"modified":1717257024,"sortOrder":82}

This is one of the 5 roll-control, this and the others one are in the attached file 
[API.Responses.zip](https://github.com/user-attachments/files/15576104/API.Responses.zip)

**Comment by mkz212** [comment]
@Kimbosmart Thank you. It will be supported from version 2.0.0. 👍

**Comment by mkz212** [comment]
@Kimbosmart version 2.0.0 published. Let us know if that help? If so, please close the Issue.

**Comment by mkz212** [comment]
@Kimbosmart 

Great! Please close the Issue.
