### ISSUE TITLE
Add thermostat compatibility

### ISSUE THREAD

**Issue by carlosdiazcat** [ilcato/homebridge-fibaro-home-center#404]
Hi, in the line 415 of fibaroAccessory.ts "case (type === 'climateZone'):" could you add case (type === 'com.fibaro.hvacSystem'): and case (type === 'com.fibaro.hvacSystemAuto'):  for normal thermostat, are other for cool or heat like heat controller device ('com.fibaro.FGT001')

**Comment by mkz212** [comment]
@carlosdiazcat 

platform.ts , lines from 164 to 178 , to understand climate and heating zones in this case. 😉

Maybe describe more what you want to achieve?
