### ISSUE TITLE
enhancement : Support for virtual thermostats ( QuickApps and Linked devices )

### ISSUE THREAD

**Issue by flipoidix** [ilcato/homebridge-fibaro-home-center#42]
Hi, 

Any chance of supporting virtual thermostats ( QuickApps and Linked devices ) ? 

Thank you

**Comment by math05** [comment]
does this mean that any QA will be supported? I'm missingsupport for QA where simple buttons are exposed to HomeKit.

**Comment by ilcato** [comment]
@math05, it can be implemented in the same way as virtual devices.

**Comment by ilcato** [comment]
@math05, I just created a QA based on binary button and it is already supported by the plugin.
