### ISSUE TITLE
Question: Recovery mode

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#435]
### Description

Hi Ilcato,

I need to enter recovery mode on my home center 2 to check a couple of things (HC2 don't boot after a power failure, it do a compete boot sequence but then hangs with no LED on, want to try a repair system).

Wanted to know if this procedure can disrupt all devices inside the home app. I have lot of devices and scenes based on them, don't want to start over.

Thanks a lot

### Plugin version

2.0.0

### Fibaro HC / Yubii Home type and firmware

Homcenter 2 4.630

**Comment by mkz212** [comment]
I don't know if anyone checked, but it's best to turn off Apple hubs for this time. Also enable in Homebridge settings "keep accessories of uninstalled plugins".

**Comment by mkz212** [comment]
As for HC2, I also had a lot of problems. Some solved the installation of the latest software, but I see that you already have it. A large part of the problems was also solved by... removing from the box - it overheated. Unfortunately, there were also problems that required a visit to the service and replace some parts.

**Comment by redeemer666** [comment]
I also tried to replace the CMOS battery, that some people suggested in forums, with no luck. I have only this last test to try otherwise will keep it that way (overheating issues also for me too, fortunately I'm not alone), but first I want to wait a little bit more to check if someone tested it. I will go nuts if I have to reconfigure all accessories inside "Home"

**Comment by ilcato** [comment]
@redeemer666 @mkz212 some HomeKit iOs apps (I don't remember which one, maybe Controller for HomeKit) allows for a configuration backup and restore capability. Never tried.

**Comment by mkz212** [comment]
@redeemer666 Try disable remote access in Fibaro HC2. I remember that it also caused a problem for me. This plugin uses local access so it will work.
