### ISSUE TITLE
No automatic reconnection

### ISSUE THREAD

**Issue by EliasADN** [ilcato/homebridge-fibaro-home-center#45]
Hello:

I have a HC3L connected by WIFI, when the connection is lost against the HC3L homebridge it does not reconnect automatically.
In the logs I can see the following errors for each device of the HC3L:
`[4/7/2021, 9:25:38 AM] [FibaroHC3] G1 - There was a problem getting value from:  42 - Err: Error: connect EHOSTUNREACH "[IP]":80`
Restarting solves the problem

Thanks!

**Comment by ilcato** [comment]
@EliasADN what are you restarting ? Homebridge or Home Center?

**Comment by EliasADN** [comment]
> @EliasADN what are you restarting ? Homebridge or Home Center?

Homebridge.
I'm using a homebridge docker with homebridge-config-ui-x, restarting the homebridge solves the problem.

**Comment by ilcato** [comment]
@EliasADN there's no fixed connection between homebridge and home center, for every request to the home center a new connection is made.
You can see. the EHOSTUNREACH when the home center is not reachable via IP.

Is the homebridge machine also connected via WiFi?

**Comment by EliasADN** [comment]
Yes, via WiFi. I have a lot of problems with HC3L and WiFi.
I have found that it ends up reconnecting after 5 to 10 minutes.

**Comment by ilcato** [comment]
> Yes, via WiFi. I have a lot of problems with HC3L and WiFi.
> I have found that it ends up reconnecting after 5 to 10 minutes.

What happens if you do not restart homebridge ? The error log you see are consistent with the situation of not having the HCL3 a Wifi connection, but after the HCL3 reconnect to Wifi homebridge should be able to execute the requests.

**Comment by ilcato** [comment]
@EliasADN any feedback?

**Comment by EliasADN** [comment]
> @EliasADN any feedback?

No, it has not happened again and I cannot reproduce it.
