### ISSUE TITLE
No response in HomeKit after few days of working perfectly fine. Restart of underbridge resolves issue for a few days again.

### ISSUE THREAD

**Issue by Ilyu321** [ilcato/homebridge-fibaro-home-center#455]
### Description

I'm using latest Hombridge on a Synology 423+ with the v2.0.0 Fibaro Plugin. Everything is working as expected via an under bridge. After a few days everything is displayed as "not responding" in the Home App but still logging states like "Light off/on" in the console in the Homebridge Web-Interface. Is this an issue on my side? Should I implement some kind of daily restart during the night? The log does not show anything relevant (to me) - On the initial start of the plugin it says "Failed to create listener for avahi-daemon server state. " and a few "device" not supported rows (example below).

### Logs

```code
Failed to create listener for avahi-daemon server state. The system will not be notified about restarts of avahi-daemon and will therefore stay undiscoverable in those instances. Error message: Error: No such interface found
[8/23/2024, 12:32:31 PM] [FibaroHC] Loading accessories
[8/23/2024, 12:32:31 PM] [FibaroHC] admin [id: 2, type: HC_user]: device not supported
[8/23/2024, 12:32:31 PM] [FibaroHC] YR Weather [id: 3, type: com.fibaro.yrWeather]: device not supported
[8/23/2024, 12:32:31 PM] [FibaroHC] 20.0.1 [id: 22, type: com.fibaro.remoteController]: device not supported
```

### Plugin version

v2.0.0

### Fibaro HC / Yubii Home type and firmware

Home Center 3

**Comment by mkz212** [comment]
@Ilyu321 

- what version of Homebridge and Homebridge UI?
- what mDNS advertiser (in Homebridge settings)?
- what Apple Hubs (Homepods? Apple TV?) and with what version of software?
- what iOS version of iPhone or macOS version (depending where you use Apple Home app)?

**Comment by Ilyu321** [comment]
Homebridge: v1.8.4 
UI: v4.56.4
mDNS advertiser: Avahi
Currently 1x current gen Homepod mini & Apple TV 4K (2022) (TV added 2 days ago) everything on auto-update (non-beta) for Germany.
Iphone with iOS 17.5.1. Just saw 17.6.1. and updating..

**Comment by mkz212** [comment]
There are known such cases if there are several Apple Hubs. That's why Apple introduced the ability to choose the main hub in iOS 18. You can install the ios 18 beta and check. Or you can turn off all hubs except one and also check this way. 

As for mDNS, probably the most popular are Bonjour and Ciao. From Homebridge 2.0 Ciao will be default.

**Comment by Ilyu321** [comment]
I can exclude the serveral Apple Hubs thesis, as I was using only the Homepod mini as only Hub and the issue was still happening. I just switched to Ciao - maybe this already fixes it. Thanks for the fast response, I'll report back if it still works after a few days.

**Comment by mkz212** [comment]
If you were curious of differences:
https://github.com/homebridge/homebridge/wiki/mDNS-Options
