### ISSUE TITLE
Slats of blinds not set

### ISSUE THREAD

**Issue by danholt-international** [ilcato/homebridge-fibaro-home-center#46]
When using a homekit automation the (in home.app) set tilt angle will not be set for the slats.
The blind itself is moving to the right position (open, closed or any position in-between) but slats do not turn.

But manually dragging the slider for the slats in home.app works fine.
So I am not sure if this issue is caused by the hc3 plugin.

**Comment by ilcato** [comment]
@danholt-international, I don't think it's related to the plugin. Unfortunately I'm not able to test the case in my environment
since I do not use such a device.
