### ISSUE TITLE
Simulate a "Garage Door" or "Gate" HK module with multiple ZWAVE devices

### ISSUE THREAD

**Issue by seduffes** [ilcato/homebridge-fibaro-home-center#471]
### Description

It would be great to create a way to emulate a HK Garage Door Opener with in Homebridge using :
- a module to Open / Close (Single push button, or dual buttons)
- sensors to define the door states (Open / Closed)

I didn't find the way to do it with the way the plugin works.

Thank you for your help.

### Plugin version

2.1.3

### Fibaro HC / Yubii Home type and firmware

Fibaro HC2

**Comment by mkz212** [comment]
If I understand corectly you want to combine door sensor and e.g. smart implant (or other device that closes for while two cables to give a signal for the gate) into one device that will create garage door in homekit - if door sensor is open then garage door is open (simulate that garage open).

**Comment by mkz212** [comment]
Workaround:
You can create a virtual device, such as a garage door, in some homebridge plugin. You will create automation - when the door sensor is open open virtual gate. And the second automation that when the sensor is closed, the gate is closed. The third automation when the virtual gateway is controlled run this smart implant or orher device that control gate.

**Comment by seduffes** [comment]
I will try that, but don't you think the automation from the sensor to open/close Virtual Gate will activate the device to control the gate ?

**Comment by mkz212** [comment]
> I will try that, but don't you think the automation from the sensor to open/close Virtual Gate will activate the device to control the gate ?

Ah.. Yes, sorry, my bad.

**Comment by seduffes** [comment]
I found that, but I unfortunately don't have a HC3. But I think it would answer my need...
https://github.com/Strik777/homebridge-fibaro-hc3-garagedoor

**Comment by seduffes** [comment]
That's it, and if I understand well, the sensor module will trigger **the state** Open / Close of the garage door (which is different from switching the open/close command done by the "switch" module ).

**Comment by mkz212** [comment]
> That's it, and if I understand well, the sensor module will trigger **the state** Open / Close of the garage door (which is different from switching the open/close command done by the "switch" module ).

In order for this solution to work properly, the created virtual garage door must:
- take the state from the ocupancy sensor, but not fire this virtual garage door when state changes. 
- on every change (open/close) run the controller that is connected to the gate (smart implant, relay, or something similar). This controller wire the cables for a moment and after, for example, 1 second it unwire.

**Comment by seduffes** [comment]
> > That's it, and if I understand well, the sensor module will trigger **the state** Open / Close of the garage door (which is different from switching the open/close command done by the "switch" module ).
> 
> In order for this solution to work properly, the created virtual garage door must:
> 
> * take the state from the ocupancy sensor, but not fire this virtual garage door when state changes.
> * on every change (open/close) run the controller that is connected to the gate (smart implant, relay, or something similar). This controller wire the cables for a moment and after, for example, 1 second it unwire.



> > That's it, and if I understand well, the sensor module will trigger **the state** Open / Close of the garage door (which is different from switching the open/close command done by the "switch" module ).
> 
> In order for this solution to work properly, the created virtual garage door must:
> 
> * take the state from the ocupancy sensor, but not fire this virtual garage door when state changes.
> * on every change (open/close) run the controller that is connected to the gate (smart implant, relay, or something similar). This controller wire the cables for a moment and after, for example, 1 second it unwire.

Correct.
I imagine something litke that : 
- when you push the "OPEN GATE" button in Homekit it triggers the "switch" to open the door/gate,
- the gate will start to open, causing the "CLOSE sensor" to change state, and you should see "OPENING" state in Home app.
- until the "OPEN sensor" is triggered --> the state changes to "OPEN" in Home app.
- when you push the "CLOSE GATE" button it triggers the "switch" module to close the gate, 
- the gate start to close, causing the "OPEN sensor" to change its state, and you see "CLOSING" state in Home app.
- until the "CLOSE sensor" is triggered, when the state changes to "CLOSED" in Home app.

The difficulty is usually gates or garage door can be opened/closed by a single push button style switch. In this case, the "OPENING" and "CLOSING" state can be emulated with configured delayed.

**Comment by mkz212** [comment]
Hmm... Everything is correct. Only this plan has one fundamental disadvantage - both: the door window sensor and the smart implant / relay must be from Fibaro, or at least zwave connected to the Fibaro hub (home center, yubi). Why does I write about it? I currently don't have any door / window sensor, and if I had to buy it, I would choose one with Matter over Thread and connect it directly to HomeKit. In addition, it is 2x cheaper.
