### ISSUE TITLE
Dimmer 2 problem. 

### ISSUE THREAD

**Issue by mkz212** [ilcato/homebridge-fibaro-home-center#48]
Dimmer 2. 
"type":"com.fibaro.FGD212",
"baseType":"com.fibaro.multilevelSwitch",
"deviceControlType":"23"

When I move the slider, the light blinks. For example, when I do from 2% to 100% it should only lighten up but it makes it brighter, darker, brighter.

And sometimes he doesn't listen. I change the value, the slider goes up and then goes back to the old position.

In other issue You say: „it seems that they are related to a bug in Home Center on the refreshState, investigating”. 

I have HCL v. 4.610 (newest). 
In Fibaro app Home Center iOS working ok.

**Comment by ilcato** [comment]
@mkz212, can you test beta version with this command:
`sudo npm install -g homebridge-fibaro-home-center@beta`
and check if the issue is solved?
Thanks

**Comment by mkz212** [comment]
Still blinking.

**Comment by ilcato** [comment]
@mkz212 can you describe a specific way to reproduce it?

**Comment by mkz212** [comment]
In Apple Home app, when I move the slider, the light blinks. For example, when I do from 2% to 100% it should only lighten up but it makes it brighter, darker, brighter. Same moving down. And sometimes few seconds for reaction. 

In Fibaro app for iOS working ok. 

In Homebridge there is no blinking, only sometimes few second for reaction.

**Comment by mkz212** [comment]
And another strange thing. I turned on the light in Homebridge, then I opened the Apple Home application, for a moment it showed that the light is off and then the application itself turned off the light.

**Comment by mkz212** [comment]
And my Fibaro Switch now show two switches per device? Before was ok.

**Comment by ilcato** [comment]
@mkz212 can you try to disable polling by setting `pollerperiod` to `"3"` and check the behaviour ?

**Comment by ilcato** [comment]
> And my Fibaro Switch now show two switches per device? Before was ok.

Can you send the json data of such a device?

**Comment by mkz212** [comment]
when i set "pollerperiod": 1 there is no blinking :) do maybe make "pollerperiod": 1 default? :)

**Comment by mkz212** [comment]
For those devices in which the switches are displayed twice. I check and in homebridge-fibaro-home-center v1.1.17  is the same. But only some devices type on/off are displayed twice (not all). 

This device is ok:

`{"id":152,"name":"Kuchnia","roomID":9,"type":"com.fibaro.binarySwitch","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":149,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","light","power","zwave","zwaveMultiChannelAssociation","zwaveProtection"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.4","RFProtectionState":"0","RFProtectionSupport":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"2","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"1","emailNotificationID":"0","emailNotificationType":"0","endPointId":"1","energy":"2.51","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"23","parametersTemplate":"781","power":"0.00","productInfo":"1,15,2,3,16,0,3,4","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000047eb6","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"reconfigure":0,"reset":0,"turnOff":0,"turnOn":0},"created":1617293275,"modified":1617293275,"sortOrder":34},`


This device is not ok (binary switch):

`{"id":286,"name":"Kuchnia pod szafkami","roomID":11,"type":"com.fibaro.binarySwitch","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":281,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","light","power","zwave","zwaveMultiChannelAssociation","zwaveProtection"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.4","RFProtectionState":"0","RFProtectionSupport":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"2","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"1","emailNotificationID":"0","emailNotificationType":"0","endPointId":"2","energy":"5.32","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"47","parametersTemplate":"781","power":"0.00","productInfo":"1,15,2,3,16,0,3,4","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000047d38","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"reconfigure":0,"reset":0,"turnOff":0,"turnOn":0},"created":1617293284,"modified":1617293284,"sortOrder":133}`

and this dimmer also is displayed twice:

`{"id":232,"name":"Kuchnia wyspa","roomID":11,"type":"com.fibaro.FGD212","baseType":"com.fibaro.multilevelSwitch","enabled":true,"visible":true,"isPlugin":false,"parentId":229,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","levelChange","light","power","zwave","zwaveAlarm","zwaveMultiChannelAssociation","zwaveProtection","zwaveSceneActivation"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.5","RFProtectionState":"0","RFProtectionSupport":"0","alarmLevel":"0","alarmType":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"23","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"15","emailNotificationID":"0","emailNotificationType":"0","endPointId":"1","energy":"3.85","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"39","parametersTemplate":"796","power":"0.00","productInfo":"1,15,1,2,16,0,3,5","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","sceneActivation":"0","serialNumber":"h'000000000006e06c","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"0"},"actions":{"reconfigure":0,"reset":0,"sceneActivationSet":0,"setValue":1,"startLevelDecrease":0,"startLevelIncrease":0,"stopLevelChange":0,"turnOff":0,"turnOn":0},"created":1617293280,"modified":1617293280,"sortOrder":134}`

**Comment by ilcato** [comment]
> when i set "pollerperiod": 1 there is no blinking :) do maybe make "pollerperiod": 1 default? :)

pollerperiod = n means that every n seconds homebridge checks for updates coming from home center. If you do not have too many devices 1s is ok.

**Comment by ilcato** [comment]
> For those devices in which the switches are displayed twice. I check and in homebridge-fibaro-home-center v1.1.17 is the same. But only some devices type on/off and some dimmers are displayed twice (not all).
> 
> This device is ok:
> 
> `{"id":152,"name":"Kuchnia","roomID":9,"type":"com.fibaro.binarySwitch","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":149,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","light","power","zwave","zwaveMultiChannelAssociation","zwaveProtection"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.4","RFProtectionState":"0","RFProtectionSupport":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"2","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"1","emailNotificationID":"0","emailNotificationType":"0","endPointId":"1","energy":"2.51","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"23","parametersTemplate":"781","power":"0.00","productInfo":"1,15,2,3,16,0,3,4","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000047eb6","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"reconfigure":0,"reset":0,"turnOff":0,"turnOn":0},"created":1617293275,"modified":1617293275,"sortOrder":34},`
> 
> This device is not ok (binary switch):
> 
> `{"id":286,"name":"Kuchnia pod szafkami","roomID":11,"type":"com.fibaro.binarySwitch","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":281,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","light","power","zwave","zwaveMultiChannelAssociation","zwaveProtection"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.4","RFProtectionState":"0","RFProtectionSupport":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"2","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"1","emailNotificationID":"0","emailNotificationType":"0","endPointId":"2","energy":"5.32","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"47","parametersTemplate":"781","power":"0.00","productInfo":"1,15,2,3,16,0,3,4","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000047d38","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"false"},"actions":{"reconfigure":0,"reset":0,"turnOff":0,"turnOn":0},"created":1617293284,"modified":1617293284,"sortOrder":133}`
> 
> and this dimmer also is displayed twice:
> 
> `{"id":232,"name":"Kuchnia wyspa","roomID":11,"type":"com.fibaro.FGD212","baseType":"com.fibaro.multilevelSwitch","enabled":true,"visible":true,"isPlugin":false,"parentId":229,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["deviceGrouping","energy","levelChange","light","power","zwave","zwaveAlarm","zwaveMultiChannelAssociation","zwaveProtection","zwaveSceneActivation"],"properties":{"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.5","RFProtectionState":"0","RFProtectionSupport":"0","alarmLevel":"0","alarmType":"0","categories":"[\"lights\"]","configured":true,"dead":"false","deadReason":"","deviceControlType":"23","deviceGroup":"[]","deviceGroupMaster":"0","deviceIcon":"15","emailNotificationID":"0","emailNotificationType":"0","endPointId":"1","energy":"3.85","isLight":"true","localProtectionState":"0","localProtectionSupport":"0","log":"","logTemp":"","manufacturer":"","markAsDead":"true","model":"","nodeId":"39","parametersTemplate":"796","power":"0.00","productInfo":"1,15,1,2,16,0,3,5","protectionExclusiveControl":"0","protectionExclusiveControlSupport":"false","protectionState":"0","protectionTimeout":"0","protectionTimeoutSupport":"false","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","sceneActivation":"0","serialNumber":"h'000000000006e06c","showEnergy":"true","smsNotificationID":"0","smsNotificationType":"0","useTemplate":"true","userDescription":"","value":"0"},"actions":{"reconfigure":0,"reset":0,"sceneActivationSet":0,"setValue":1,"startLevelDecrease":0,"startLevelIncrease":0,"stopLevelChange":0,"turnOff":0,"turnOn":0},"created":1617293280,"modified":1617293280,"sortOrder":134}`

Both the duplicated device works or only one? Maybe you have a corrupted cached accessory. If you have homebridge ui you can try to delete from the accessories cache the specific devices otherwise you can remove the whole accessories folder but in that case you will lose all the automations you have created.

**Comment by mkz212** [comment]
Only one works. Eg. In "Kuchnia wyspa" Left switch is on/off (wrong, not working switch) , right is multilevel switch and this is correct. 

Ok deleting cache solved problem :)

**Comment by mkz212** [comment]
Yes. Thank You for help. :)

**Comment by mkz212** [comment]
Sorry. I said too quickly that it works properly. Even after setting the pollerperiod to 3, it still flashes usind multilevel switch (Fibaro Dimmer 2)

**Comment by mkz212** [comment]
I also checked in the second Home Center Lite and the same. HCL v4.610.

**Comment by ilcato** [comment]
@mkz212 weren’t you using a 1s poller prior?

**Comment by mkz212** [comment]
I check with 1s, 3s and even 10s.

**Comment by ilcato** [comment]
@mkz212, I'm using bet version since a week and I have no problem with setting dimmers via home app. Publishing it.
