### ISSUE TITLE
 Error getting data from Home Center:

### ISSUE THREAD

**Issue by AshenPaladin** [ilcato/homebridge-fibaro-home-center#508]
### Description

Ever since the latest update to the plugin, that being 3.1.0, I'm getting an error with " Error getting data from Home Center:". The devices still work a little within Apple Home, but they usually disconnect and/or have issues. 

 
 I'm a little lost here because the plugin worked perfectly before the update, and I am certain that the IP, username and password are all correct, 

### Logs

```code
[10/16/2024, 1:35:36 PM] [FibaroHC] Error getting data from Home Center:  SyntaxError: Unexpected token 'o', "[object Obj"... is not valid JSON
    at JSON.parse (<anonymous>)
    at remoteController (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/deviceAuto.ts:379:46)
    at FibaroAccessory.configureAccessoryFromType (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:439:35)
    at new FibaroAccessory (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:52:40)
    at FibaroHC.addAccessory (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:332:18)
    at /volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:253:14
    at Array.map (<anonymous>)
    at FibaroHC.processDevices (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:236:18)
    at FibaroHC.login (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/platform.ts:153:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[10/16/2024, 1:35:36 PM] [FibaroHC] Make sure you provide the correct data: URL or IP, username and password and that HC is enabled and available on the same network as Homebridge. Using https may be mandatory if you configured HC to use it.
[10/16/2024, 1:35:36 PM] [FibaroHC] Next try in 5 minutes
[10/16/2024, 1:36:09 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at FibaroAccessory.getCharacteristicValue (/volume1/homebridge/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:293:7)
```

### Plugin config

```JSON
{
    "name": "FibaroHC",
    "url": "",
    "username": "",
    "password": "",
    "pollerperiod": 3,
    "markDeadDevices": false,
    "thermostattimeout": 7200,
    "thermostatmaxtemperature": 100,
    "adminUsername": "",
    "adminPassword": "",
    "securitysystem": "disabled",
    "addRoomNameToDeviceName": "disabled",
    "logsLevel": 1,
    "devices": [
        {
            "displayAs": "switch"
        }
    ],
    "platform": "FibaroHC"
}
```

### Plugin version

3.1.0

### Fibaro HC / Yubii Home type and firmware

Fibaro Home Center 3, v5.160.42

**Comment by ilcato** [comment]
@AshenPaladin, was the problem present in 3.0.0 ?

**Comment by rafalantas** [comment]
same for me after updating to 3.1.0 had to revert back to 3.0.0

**Comment by ilcato** [comment]
ok, so it is a problem of the 3.1.0. Let me check. I'm using it since the release and also the betas 
without problems.

**Comment by ilcato** [comment]
@AshenPaladin , @rafalantas do you have remote controllers in you Fibaro Home centers? If yes which one?

**Comment by rafalantas** [comment]
I have Fibaro Button

**Comment by AshenPaladin** [comment]
> @AshenPaladin , @rafalantas do you have remote controllers in you Fibaro Home centers? If yes which one?

I do not have any remote controllers

**Comment by ilcato** [comment]
@rafalantas, Ok. Can you past the API response for device?

**Comment by ilcato** [comment]
> > @AshenPaladin , @rafalantas do you have remote controllers in you Fibaro Home centers? If yes which one?
> 
> I do not have any remote controllers

@AshenPaladin, ok. Can you post the logs printed before the error? A few lines is sufficient.

**Comment by AshenPaladin** [comment]
> > > @AshenPaladin , @rafalantas do you have remote controllers in you Fibaro Home centers? If yes which one?
> > 
> > 
> > I do not have any remote controllers
> 
> @AshenPaladin, ok. Can you post the logs printed before the error? A few lines is sufficient.

The only lines from Fibaro Home Center in the logs before the error are these
`[10/16/2024, 2:18:54 PM] [FibaroHC] Device dead:  27  service: Senzor Apa Baie Etaj Battery, reason: connection
[10/16/2024, 2:18:54 PM] [FibaroHC] Device dead:  27  service: Senzor Apa Baie Etaj, reason: connection
[10/16/2024, 2:18:54 PM] [FibaroHC] Device dead:  27  service: Senzor Apa Baie Etaj Battery, reason: connection`

But the sensor also appears are disconnected in the Yubii Home app and I was going to replace its battery

Other than that I can provide other logs but they're from the other two plugins that I'm using, Midea Platform and Camera FFMPEG

**Comment by ilcato** [comment]
@AshenPaladin  @rafalantas can you test 3.1.1-beta.1 ?

@AshenPaladin this should also fix the other error I see in the initial log you provided.

**Comment by AshenPaladin** [comment]
Thank you very much, with the update to the beta version that you suggested the error no longer appears and the devices seem to be working properly

**Comment by ilcato** [comment]
@rafalantas is it ok also for you? Are you able to program the Fibaro Button?

**Comment by Damianod27** [comment]
Hello. I have the same situation. Everything worked properly until version 3.0. Version 3.1 and 3.1.1 beta 1 generate an error. Some Fibaro Wall Plug devices do not respond in HomeKit. However, they can be controlled after entering the building. Additionally, after the update, the devices shown in the pictures were removed and added again in HomeKit. The automations that these devices contained must be reconfigured. Regards

![IMG_6138](https://github.com/user-attachments/assets/c33cb105-0b69-437d-a8b0-94b0d959fd04)
![IMG_6139](https://github.com/user-attachments/assets/68cfffb1-8e8b-4360-949b-a92ed60dcfb3)
![IMG_6140](https://github.com/user-attachments/assets/30574888-c35e-4fba-8f63-d4c9d6e15985)

**Comment by ilcato** [comment]
> Hello. I have the same situation. Everything worked properly until version 3.0. Version 3.1 and 3.1.1 beta 1 generate an error. 

@Damianod27 do you have some logs for the error you mention? Additionally what do you mean with 

>  However, they can be controlled after entering the building.

?

**Comment by Damianod27** [comment]
I also noticed that after updating the plugin in the json file there is the correct configuration of the Fibaro plugin. However, if you go directly to the Fibaro plugin settings, the Host field is empty.

**Comment by Damianod27** [comment]
> > Hello. I have the same situation. Everything worked properly until version 3.0. Version 3.1 and 3.1.1 beta 1 generate an error.
> 
> @Damianod27 do you have some logs for the error you mention? Additionally what do you mean with
> 
> > However, they can be controlled after entering the building.
> 
> ?

There are no errors in the Homebridge logs. It looks just like the pictures.

![IMG_6141](https://github.com/user-attachments/assets/b83d926b-c640-495e-b1b6-efd9ea811e74)

![IMG_6142](https://github.com/user-attachments/assets/b246a86a-8095-4f06-a81f-87bbf3e5d8b3)
![IMG_6143](https://github.com/user-attachments/assets/b47bbc75-5d51-4c67-a1e8-71795e0647f0)

**Comment by ilcato** [comment]
@Damianod27 can you post the API response for a device with this problem ?

**Comment by Damianod27** [comment]
> @Damianod27 can you post the API response for a device with this problem ?
> 
> 

Can you remind me of the link to that? I can't remember. I did it quite a while ago.

**Comment by Damianod27** [comment]
@ilcato 

Now I noticed some strange log entries in Homebridge. I only turned the lamp off once and turned it on once. Up to that point there were 6 entries

![image](https://github.com/user-attachments/assets/f1026765-c8a0-492e-bc2c-f44c75696d3c)

**Comment by ilcato** [comment]
> > @Damianod27 can you post the API response for a device with this problem ?
> 
> Can you remind me of the link to that? I can't remember. I did it quite a while ago.

It's in the readme

**Comment by ilcato** [comment]
@Damianod27 I think I understood, but I need that info. See the readme on how to get the API response.

**Comment by Damianod27** [comment]
@ilcato Here you go :-). 

I also tried deleting the accessory from the Homebridge cache so that it would re-add itself. Unfortunately, the result is identical.

![image](https://github.com/user-attachments/assets/fc20f75d-2da1-404b-aeeb-c3c7b95ffdc0)

![image](https://github.com/user-attachments/assets/3fe7be4a-6fc9-4b28-be8b-cac7da19cf33)

**Comment by ilcato** [comment]
@Damianod27 can you send it as a text file? I have exactly the same device and it works. But I need to compare field by field the data in order to understand if there's something different.

You can confirm also that with version 3.0.0 it works ?

**Comment by Damianod27** [comment]
I personally have a lot of Fibaro Wall Plugs but only some of them have this problem. The rest work fine. Yes, on version 3.0 everything was ok.

[Fibaro Wall Plug.txt](https://github.com/user-attachments/files/17399905/Fibaro.Wall.Plug.txt)

**Comment by ilcato** [comment]
@Damianod27 the only thing significant diverse is the property color that in my case is "off" and with your device is "white". 

Can you check the corresponding value for a device that is working well?

**Comment by Damianod27** [comment]
> @Damianod27 the only thing significant diverse is the property color that in my case is "off" and with your device is "white".
> 
> Can you check the corresponding value for a device that is working well?

@ilcato 

This is a Wall Plug, so you can't control the colors of the device, only the colors of the ring.

**Comment by ilcato** [comment]
@Damianod27 ok.

Do you have logs set as All Logs in the configuration of the plugin?

Do you see in the log something like: 

`Lampa TV [123]: getting On`

?

**Comment by ilcato** [comment]
@Damianod27 can you also create another issue, please? Copy only your first post.

This is definitely not the same case as described by this issue. Thanks

**Comment by ilcato** [comment]
> Thank you very much, with the update to the beta version that you suggested the error no longer appears and the devices seem to be working properly

@AshenPaladin can you close the issue please? I will release 3.1.1 in a few days.
