### ISSUE TITLE
Problem with some Fibaro Wall Plugs with plug version 3.1 and 3.1.1. Beta 1

### ISSUE THREAD

**Issue by Damianod27** [ilcato/homebridge-fibaro-home-center#510]
### Description

Hello. I have the same situation. Everything worked properly until version 3.0. Version 3.1 and 3.1.1 beta 1 generate an error. Some Fibaro Wall Plug devices do not respond in HomeKit. However, they can be controlled after entering the building. Additionally, after the update, the devices shown in the pictures were removed and added again in HomeKit. The automations that these devices contained must be reconfigured. Regards

### Plugin config

```JSON
{
            "name": "FibaroHC",
            "url": "xxxxxxxx",
            "username": "xxxxxxx",
            "password": "xxxxxxxxxxxx",
            "pollerperiod": 2,
            "markDeadDevices": false,
            "thermostattimeout": 7200,
            "thermostatmaxtemperature": 100,
            "securitysystem": "disabled",
            "addRoomNameToDeviceName": "disabled",
            "logsLevel": 1,
            "devices": [
                {
                    "displayAs": "switch"
                }
```

### Plugin version

3.1 or 3.1.1 beta 1

### Fibaro HC / Yubii Home type and firmware

FHC 2 ver.4.630

**Comment by Damianod27** [comment]
@ilcato 

Log information in the Homebridge plugin in the picture : 
![Logs_FHC](https://github.com/user-attachments/assets/e2738022-c61d-4c25-9f0c-72c9aa978cec)

I have looked through all the information in the Homebridge logs and I do not see any such entry: "TV Lamp [123]: getting On"

Most of the Wall Plug versions I have are 102. There are also a few 101s. I don't think it matters though. All Wall Plugs in version 102 have software 3.2. Some work fine, others don't.

**Comment by Damianod27** [comment]
@ilcato 

Example has another Wall Plug which has a problem. One turn on and off generates so many logs in Homebridge. I don't remember anything like that ever happening.

![aa](https://github.com/user-attachments/assets/8b4b6145-beca-4619-9f61-fe767c9781f8)

**Comment by ilcato** [comment]
> @ilcato
> 
> 1. Log information in the Homebridge plugin in the picture :


@Damianod27 can you set the log level to "All logs", reboot and look at the logs again ?

**Comment by Damianod27** [comment]
> > @ilcato
> > 
> > 1. Informacje z dziennika wtyczki Homebridge na obrazku:
> 
> @Damianod27Czy możesz ustawić poziom rejestrowania na „Wszystkie rejestry”, zrestartować komputer i ponownie przejrzeć rejestry?

@ilcato Give me 10 minutes and I'll send you that log information

I'm sending you photos from HC2 so you can see how many Wall Plugs I have. There are exactly 21 and only 6 are working incorrectly. In Homekit they are marked as "accessory not responding". When you go inside, as I already informed in another post, you can control them without any problems.

![f1](https://github.com/user-attachments/assets/aecac9c7-bb7d-45b7-8d6a-fe4a49aad837)

![F2](https://github.com/user-attachments/assets/f874bc12-73dc-4834-9dba-33bab4c09318)

![f3](https://github.com/user-attachments/assets/a699d283-f403-4de6-9b56-f0b7550a07b1)

![f4](https://github.com/user-attachments/assets/41409f50-7747-4c4c-be16-cf54a74ac77f)

**Comment by ilcato** [comment]
@Damianod27 interesting. I didn't notice that you are on an HC2. hmmm.

**Comment by Damianod27** [comment]
@ilcato 

I've enabled a few devices to get the logs to appear. Note that the problem devices generate too many logs in Homebridge.

[homebridge-fibaro-home-center.log (1).txt](https://github.com/user-attachments/files/17401771/homebridge-fibaro-home-center.log.1.txt)

**Comment by ilcato** [comment]
@Damianod27, I'm almost sure to have found the problem.
The json file that you provided to me contains a property called `deviceControlType` that I used to set the right type of device. The value of that property is `"2"` that  corresponds to a light. In this way a create a lamp and not a wall plug in HomeKit. In the plugin I compare it to 2 and there's no match resulting in a new device type (this is the reason homebridge regenerated the accessory.
My Fibaro Wall plug return a value of `2` not as a string value and it is correctly mapped to a Lightbulb.

I can easily modify the plugin in order to accept also a string but I'm wondering if the wall plugs that are working in your setup are returning a string or a number for that property. Can you check please?

In the past I found HC returning inconsistent value type on the API, but only for true/false values (returned as "true"/"false".

I don't understand why with the 3.0.0 works though.

**Comment by Damianod27** [comment]
> @Damianod27, Jestem prawie pewien, że znalazłem problem. Plik json, który mi dostarczyłeś, zawiera właściwość o nazwie `deviceControlType`, której użyłem do ustawienia właściwego typu urządzenia. Wartość tej właściwości `"2"`odpowiada światłu. W ten sposób w HomeKit stwórz lampę, a nie wtyczkę ścienną. We wtyczce porównuję ją do 2 i nie ma dopasowania, co skutkuje nowym typem urządzenia (to jest powód, dla którego Homebridge zregenerował akcesorium). Moja wtyczka ścienna Fibaro zwraca wartość `2`nie jako wartość ciągu i jest ona poprawnie mapowana na żarówkę.
> 
> Mogę łatwo zmodyfikować wtyczkę, aby akceptowała również ciąg, ale zastanawiam się, czy wtyczki ścienne, które działają w Twojej konfiguracji, zwracają ciąg lub liczbę dla tej właściwości. Czy możesz to sprawdzić?
> 
> W przeszłości zauważyłem, że HC zwraca niespójny typ wartości w API, ale tylko w przypadku wartości prawda/fałsz (zwracanych jako „prawda”/„fałsz”).
> 
> Nie rozumiem jednak, dlaczego działa w wersji 3.0.0.

@ilcato 

Should I remove something from the configuration file to avoid this problem?

**Comment by ilcato** [comment]
@Damianod27 no I will release a new beta, but please check the API result for a working device.

**Comment by Damianod27** [comment]
> @Damianod27nie, opublikuję nową wersję beta, ale sprawdź proszę wynik API pod kątem działającego urządzenia.

@ilcato 

I'm sorry but I don't understand what to do

**Comment by ilcato** [comment]
Get the ID of a Fibaro Wallplug that is working and call the API to get the json file similar to the one you already provided to me for Lampa TV.

**Comment by Damianod27** [comment]
Is this the file you're talking about? The same one as before? I've generated it now.

Fibaro Wall Plug.txt](https://github.com/user-attachments/files/17402010/Fibaro.Wall.Plug.txt)


See what I noticed in Homekit. How can I fix it? I tried removing the accessory from the Homebridge cache but it re-added the same way

**Comment by ilcato** [comment]
@Damianod27 exactly this is the problem. But you send me the same file as before. I need one corresponding to a functioning device not Lampa TV.

**Comment by Damianod27** [comment]
@ilcato 

Sorry I didn't click Save to File.

[Fibaro Wall Plug.txt](https://github.com/user-attachments/files/17402060/Fibaro.Wall.Plug.txt)

**Comment by ilcato** [comment]
@Damianod27 can you check version 3.1.1-beta.2 ?

You should also remove from the accessories cache the device not working (you can use the homebridge UI).

And then reboot.

**Comment by Damianod27** [comment]
> @Damianod27 can you check version 3.1.1-beta.2 ?
> 
> You should also remove from the accessories cache the device not working (you can use the homebridge UI).
> 
> And then reboot.

@ilcato 

I wrote to you above that I did this and it doesn't help. The device is added again incorrectly

![aaaaa](https://github.com/user-attachments/assets/e87a6d3e-b04e-409d-9dbc-fb60392d60e0)

**Comment by ilcato** [comment]
@Damianod27 you must install the new beta

**Comment by Damianod27** [comment]
@ilcato 

For me it's a bit strange. I tried to change the settings in HC2 of the "Lampa TV" device. I changed from light to TV. I removed the accessory from the Homebridge cache. I Full restarted Homebridge and the same problem was still visible in Homekit. After this change it should be ok but it wasn't. I currently installed beta version 2. I removed the "Lampa TV" accessory from Homebridge. I restarted Homebridge. After fully starting Homebridge I went into Homekit and look what I found. Below is a photo. Information "Incompatible" and "The Home application does not currently support this accessory". I did nothing else and after about 5 minutes everything started working properly by itself. I didn't even have to remove the other 5 non-working devices from the cache because they started working properly by themselves after about 5 minutes.

**Comment by Damianod27** [comment]
@ilcato I have now tested everything and it seems to be ok. Thank you very much for your help.

**Comment by ilcato** [comment]
@Damianod27 I do not have have HC2. Did you upgrade the firmware recently?

**Comment by Damianod27** [comment]
I haven't updated the software in quite some time. There has been no update.

**Comment by ilcato** [comment]
ok. Can you close the issue please? And  thanks for the collaboration.

**Comment by ilcato** [comment]
@Damianod27 I will release the 3.1.1 in a few days.

**Comment by Damianod27** [comment]
@ilcato I've already closed it. After updating to beta 4, my FGWDS221 devices were removed and added back to HomeKit
