### ISSUE TITLE
com.fibaro.binarySwitch in homebridge shows like  Lightbulb

### ISSUE THREAD

**Issue by h3roin** [ilcato/homebridge-fibaro-home-center#52]
com.fibaro.binarySwitch showed in home app as a "lightbulb" type of device, what makes some misunderstanding with manage home, previously on HC2 plugin it was pulled correctly with "switch" type to homebridge.
![image](https://user-images.githubusercontent.com/35816235/117220330-ade2da80-ae0f-11eb-8b8f-ff66a329d0a0.png)

**Comment by h3roin** [comment]
`case 'com.fibaro.binarySwitch':
          case 'com.fibaro.developer.bxs.virtualBinarySwitch':
          case 'com.fibaro.satelOutput':
          case 'com.fibaro.FGWDS221':
            switch (parseInt(this.device.properties.deviceControlType)) {
              case 2: // Lighting
              case 5: // Bedside Lamp
              case 7: // Wall Lamp
                service = this.platform.Service.Lightbulb;
                this.mainCharacteristics = [this.platform.Characteristic.On];
                break;
              case 25: // Video gate open
                service = this.platform.Service.LockMechanism;
                subtype = device.id + '--' + 'LOCK';
                this.mainCharacteristics = [this.platform.Characteristic.LockCurrentState, this.platform.Characteristic.LockTargetState];
                break;
              default:
                service = this.platform.Service.Switch;
                this.mainCharacteristics = [this.platform.Characteristic.On];
                break;
            }
            break;`

I found this part of code in "fibaroAccessory.ts" and as i see its can be in 3 types but how i can switch between them?

**Comment by ilcato** [comment]
@h3roin, can you show me the device configuration in HC? Which version of HC do you have?

**Comment by mkz212** [comment]
@h3roin Jeśli problem nadal nie został rozwiązany to #157
