### ISSUE TITLE
Cannot add more than 100 devices - issue in in version >3.x

### ISSUE THREAD

**Issue by mkrecek234** [ilcato/homebridge-fibaro-home-center#520]
### Description

When upgrading from 2.1 to 3.x I get the following error - HC2 is unusable then in Homebridge. Downgrading solves the issue immediately. The config.json is simply setup with a local IP address. Hope you can fix this issue. 

Error getting data from Home Cente
r :
Error: Cannot add more than 100 services to a single accessory! at Accessory addService (/volumel/homebridge/node_modules/homebrid
ge/node_modules/hap-nodejs/src/lib/Accessory.ts:568:13)
at PlatformAccessory.addService (/volumel/homebridge/node_modules/
homebridge/src/platformAccessory.ts:99:41)
at /volumel/homebridge/node_modules/homebridge-fibaro-home-center/
src/fibaroAccessory.ts: 98:28
at Array. forEach (<anonymous>)
at new FibaroAccessory (/volumel/homebridge/node_modules/homebridg
e-fibaro-home-center/src/fibaroAccessory.ts:94:31)
at FibaroC.addAccessory (/volumel/homebridge/node_modules/homebri
dge-fibaro-home-center/src/platform.ts: 332:18)
at /volumel/homebridge/node_modules/homebridge-fibaro-home-center/
src/platform.ts: 253:14
at Array-map (<anonymous>)
at FibaroC processDevices (/volumel/homebridge/node_modules/homeb

### Plugin version

3.1.1

### Fibaro HC / Yubii Home type and firmware

HC2

**Comment by ilcato** [comment]
@mkrecek234 do you have remotes connected to Home Center?

**Comment by mkrecek234** [comment]
> @mkrecek234 do you have remotes connected to Home Center?

You mean like a Fibaro Fob or other remotes to switch devices? Yes, I do have a few.

**Comment by ilcato** [comment]
@mkrecek234 yes. Can you list each device type and the json data corresponding to each type?
The last version add support for remotes but I only have a few type and for sure not the Fibaro Fob.
If you want to upgrade to 3.1.1 you must exclude such devices from the access right of the user that you configured in the plugin (or rename them with an "_" at the beginning of the name).

**Comment by mkrecek234** [comment]
Here is a list of all devices and their types @ilcato 
[fibarodevices.txt](https://github.com/user-attachments/files/17474633/fibarodevices.txt)

**Comment by mkrecek234** [comment]
@ilcato Here is a list of all types and devices
[fibarodevices.txt](https://github.com/user-attachments/files/17474763/fibarodevices.txt)

**Comment by ilcato** [comment]
@mkrecek234 can you test v3.2.0-beta.1 ?

**Comment by mkrecek234** [comment]
@ilcato Just installed it and all seems to run smoothly 👍

(only a unrelated "warning" which is another topic with 10/22/2024, 1:10:58 PM] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info."....

**Comment by ilcato** [comment]
@mkrecek234 thank you. Please close this issue and open a new one with the details.

**Comment by ilcato** [comment]
@mkrecek234 you should be able to see your remote in HomeKit and associate actions.
