### ISSUE TITLE
Warning for wrong temperature (uncritical)

### ISSUE THREAD

**Issue by mkrecek234** [ilcato/homebridge-fibaro-home-center#521]
### Description

 This "warning" occurs in one of my Fibaro devices: 10/22/2024, 1:10:58 PM] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info."..

Not critical as just a warning, but just to let you know

### Plugin version

3.2.0.beta1

### Fibaro HC / Yubii Home type and firmware

HC2

**Comment by ilcato** [comment]
@mkrecek234 are you able to tell me which device is? Do you have thermostats ('com.fibaro.thermostatDanfoss' or 'com.fibaro.FGT001')?

**Comment by mkrecek234** [comment]
@ilcato Can only find this related to heating zone (to be frank I am not actively using it): 
`
{"id":662,"name":"Thermostat & Heating Zone","roomID":0,"type":"com.fibaro.setPointForwarder","baseType":"com.fibaro.device","enabled":true,"visible":true,"isPlugin":true,"parentId":0,"remoteGatewayId":0,"viewXml":true,"configXml":true,"interfaces":[],"view":[],"properties":{"categories":"[\"other\"]","dead":"false","deadReason":"","deviceControlType":"0","deviceIcon":"28","emailNotificationID":"0","emailNotificationType":"0","lastSetPointValue":"0.00","log":"","logTemp":"","manufacturer":"","model":"","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","selectedHeatingZone":"---","selectedManualTime":"","selectedSetPoint":"---","smsNotificationID":"0","smsNotificationType":"0","table":"[]","ui.config.section1.caption":"Configuration","ui.config.section1.enabled":true,"ui.config.selectedHeatingZone.caption":"Heating zone","ui.config.selectedHeatingZone.enabled":true,"ui.config.selectedManualTime.caption":"Manual time","ui.config.selectedManualTime.enabled":true,"ui.config.selectedSetPoint.caption":"Thermostat","ui.config.selectedSetPoint.enabled":true,"ui.configurationStatus.caption":"{color:#C12F2F}Plugin not configured.{color} Please go to Advanced tab to setup the plugin.","ui.forceSync.caption":"Force zone temp. as set on thermostat","ui.heatingZoneStatus.caption":"Heating zone:","ui.heatingZoneStatusId.caption":"none","ui.setPointStatus.caption":"Thermostat:","ui.setPointStatusId.caption":"none","userDescription":""},"actions":{},"created":1723181833,"modified":1723181833,"sortOrder":262},{"id":669,"name":"669","roomID":0,"type":"com.fibaro.zwaveDevice","baseType":"com.fibaro.device","enabled":true,"visible":false,"isPlugin":false,"parentId":1,"remoteGatewayId":0,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveAssociation","zwaveConfiguration","zwaveMultiChannelAssociation","zwaveSlaveRouting","zwaveWakeup"],"properties":{"batteryLevel":"100","batteryLowNotification":"true","categories":"[\"other\"]","configured":true,"dead":"false","deadReason":"","defInterval":"0","deviceControlType":"0","deviceIcon":"28","deviceSpecificData":"h'0000000000057dcb","deviceSpecificIdType":"Serial Number","deviceState":"Configured","emailNotificationID":"0","emailNotificationType":"0","endPointId":"0","lastWorkingRoute":"[1]","lastWorkingRouteRequestStatus":"ok","lastWorkingRouteRequestTimestamp":"0","lastWorkingRouteResponseTimestamp":"1723181904","log":"","logTemp":"","manufacturer":"","markAsDead":"true","maxInterval":"0","minInterval":"0","model":"","neighborList":"[1,4,20,143,146,155,181,186,219,224,235,328,338,379,465,476,481,536,608,611,712,755,840,851,860,877]","neighborListRequestStatus":"ok","neighborListRequestTimestamp":"0","neighborListResponseTimestamp":"1723181904","nodeId":"159","parameters":[{"id":1,"lastReportedValue":15,"lastSetValue":15,"size":2,"value":15},{"id":2,"lastReportedValue":2,"lastSetValue":2,"size":1,"value":2},{"id":3,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":4,"lastReportedValue":2,"lastSetValue":2,"size":1,"value":2},{"id":6,"lastReportedValue":5,"lastSetValue":5,"size":2,"value":5},{"id":8,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":9,"lastReportedValue":200,"lastSetValue":200,"size":2,"value":200},{"id":12,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":14,"lastReportedValue":255,"lastSetValue":255,"size":2,"value":255},{"id":16,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":18,"lastReportedValue":15,"lastSetValue":15,"size":1,"value":15},{"id":20,"lastReportedValue":20,"lastSetValue":20,"size":1,"value":20},{"id":22,"lastReportedValue":30,"lastSetValue":30,"size":2,"value":30},{"id":24,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":25,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":28,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":29,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":40,"lastReportedValue":200,"lastSetValue":200,"size":2,"value":200},{"id":42,"lastReportedValue":3600,"lastSetValue":3600,"size":2,"value":3600},{"id":60,"lastReportedValue":20,"lastSetValue":20,"size":2,"value":20},{"id":62,"lastReportedValue":900,"lastSetValue":900,"size":2,"value":900},{"id":64,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":66,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":80,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":81,"lastReportedValue":50,"lastSetValue":50,"size":1,"value":50},{"id":82,"lastReportedValue":100,"lastSetValue":100,"size":2,"value":100},{"id":83,"lastReportedValue":1000,"lastSetValue":1000,"size":2,"value":1000},{"id":86,"lastReportedValue":18,"lastSetValue":18,"size":2,"value":18},{"id":87,"lastReportedValue":28,"lastSetValue":28,"size":2,"value":28},{"id":89,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1}],"parametersTemplate":"712","pollingTimeSec":0,"productInfo":"1,15,8,1,16,1,3,2","pushNotificationID":"0","pushNotificationType":"0","remoteGatewayId":"0","saveLogs":"true","serialNumber":"h'0000000000057dcb","smsNotificationID":"0","smsNotificationType":"0","stepInterval":"0","useTemplate":"true","userDescripti
`

**Comment by ilcato** [comment]
@mkrecek234 can you test 3.2.0-beta.2 ?

**Comment by mkrecek234** [comment]
@ilcato Still same warning, not sure if it relates to another device:
`
[10/22/2024, 2:53:42 PM] [homebridge-fibaro-home-center] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.
`

**Comment by ilcato** [comment]
@mkrecek234 can you set homebridge in debug mode so it shows details info on this ? Thanks

**Comment by ilcato** [comment]
@mkrecek234 what's there before the warning in the log?

**Comment by ilcato** [comment]
@mkrecek234 can you also test 3.2.0-beta.3. Thanks

**Comment by mkrecek234** [comment]
@ilcato Tested an no warning anymore (not sure but has this warning been there before or did it arise from this latest beta in my Homebridge ? [
10/22/2024, 6:29:31 PM] The plugin "homebridge-fibaro-home-center" requires Node.js version of ^18.20.4 || ^20.16.0 || ^22.5.1 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

**Comment by ilcato** [comment]
@mkrecek234 thank you for the report. Regard the warning of this morning, maybe my latest beta fixes it.

On the node warning, it's better if you upgrade nodejs to a more recent one, since you are on the 20.9.0 migrate to 20.18.0.

Please close the issue and if it reappears file a new report.

I will release the 3.2.0 version soon.

**Comment by ilcato** [comment]
@mkrecek234 released
