### ISSUE TITLE
"Nice" garage door not recognized

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#53]
Hi ilCato,

just switched to the new plugin, and appeared an issue that I had before on Home Center 2:

https://github.com/ilcato/homebridge-Fibaro-HC2/issues/200

Can you add it on the new one? Thanks

**Comment by redeemer666** [comment]
Quick update, workaround still works, it is changed the file you have to modify though

cd /usr/local/lib/node_modules/homebridge-fibaro-home-center/dist/
sudo nano fibaroAccessory.js (instead of Shadow.js)

**Comment by ilcato** [comment]
@redeemer666, it will be in release 2.3.3
