### ISSUE TITLE
Battery status not reported on devices

### ISSUE THREAD

**Issue by redeemer666** [ilcato/homebridge-fibaro-home-center#54]
Hi Again,

Another thing I have noticed has been "lost" after the switch: all batteries powered devices reports as "0%" on battery level. On the old plugin the battery status showed correctly.

Not a big hassle, just to pinpoint the issue

**Comment by naspinec** [comment]
Hi,

I have the same effect. Is it possible to have an estimate date of resolution?

Thanks à lot for the job.

**Comment by ilcato** [comment]
@redeemer666, @naspinec I have several battery powered devices that report correctly the battery level on HC3. Which devices do you have? Are all presenting the problem?

**Comment by ilcato** [comment]
@redeemer666, can you test the beta version?
With: `npm install -g homebridge-fibaro-home-center@beta`

**Comment by redeemer666** [comment]
Hi Again,

With your latest version (1.2.2) issue has been solved. Beta not needed, so thanks a lot for your kindness

**Comment by ilcato** [comment]
ok.

**Comment by naspinec** [comment]
Hi ilcato.

Same for me, I use an hc2 and with the old plugin the battery level was correctly reported. 

Regards.
