### ISSUE TITLE
HC2 no longer shows VD as accessories

### ISSUE THREAD

**Issue by Cameleon99** [ilcato/homebridge-fibaro-home-center#55]
Hi Ilcato,

Used an old version of the plugin and Homebridge for a long time but recently decided to update everything so that I can use the Homebridge GUI. Done a new install on latest Homebridge RPi distro and installed the current plugin. Everything works as expected other than VD's I have dont come across as switches. Has the behaviour changed sometime? Or have I missed something in the setup. The config looks near identical and can't see anything different that would cause it. 

Thanks.

EDIT: Here is the log from the new plugin...

> [30/05/2021, 11:50:24] [FibaroHC] Adding new accessory: Motion Sensor
> [30/05/2021, 11:50:24] [FibaroHC] Adding new accessory: Temp Sensor (Motion)
> [30/05/2021, 11:50:24] [FibaroHC] Adding new accessory: Light Sensor
> [30/05/2021, 11:50:24] [FibaroHC] Adding new accessory: Door Sensor
> [30/05/2021, 11:50:24] [FibaroHC] Adding new accessory: Door Sensor
> [30/05/2021, 11:50:25] [FibaroHC] Adding new accessory: Floor Lamp
> [30/05/2021, 11:50:25] [FibaroHC] Adding new accessory: Dining Light
> [30/05/2021, 11:50:25] [FibaroHC] Adding new accessory: netatmo Indoor Temp
> [30/05/2021, 11:50:25] [FibaroHC] Adding new accessory: netatmo Indoor Humid
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: netatmo Outdoor Temp
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: netatmo Outdoor Humi
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: Dishwasher
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: Washing Machine
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: Wall Lamps
> [30/05/2021, 11:50:26] [FibaroHC] Adding new accessory: HW Cylinder
> [30/05/2021, 11:50:27] [FibaroHC] Adding new accessory: Immersion Heater
> [30/05/2021, 11:50:27] [FibaroHC] Adding new accessory: FibaroSecuritySystem

And the old HC2 plugin:

> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Motion Sensor
> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Temp Sensor (Motion)
> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Light Sensor
> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Door Sensor
> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Door Sensor
> [30/05/2021, 11:43:26] [FibaroHC2] Added/changed accessory:  Floor Lamp
> [30/05/2021, 11:43:27] [FibaroHC2] Added/changed accessory:  netatmo Wind Gauge
> [30/05/2021, 11:43:27] [FibaroHC2] Added/changed accessory:  Dining Light
> [30/05/2021, 11:43:27] [FibaroHC2] Added/changed accessory:  netatmo Indoor Temp
> [30/05/2021, 11:43:27] [FibaroHC2] Added/changed accessory:  netatmo Indoor Humid
> [30/05/2021, 11:43:27] [FibaroHC2] Added/changed accessory:  netatmo Outdoor Temp
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  netatmo Outdoor Humi
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  Kitchen Lights
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  Living Lights
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  Bedroom Lights
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  State Scenes
> [30/05/2021, 11:43:28] [FibaroHC2] Added/changed accessory:  Dishwasher
> [30/05/2021, 11:43:29] [FibaroHC2] Added/changed accessory:  Washing Machine
> [30/05/2021, 11:43:29] [FibaroHC2] Added/changed accessory:  Wall Lamps
> [30/05/2021, 11:43:29] [FibaroHC2] Added/changed accessory:  HW Cylinder
> [30/05/2021, 11:43:29] [FibaroHC2] Added/changed accessory:  Immersion Heater

Kitchen Lights, Living Light, Bedroom Lights and State Scenes are VDs that run scenes to control the lights in those rooms or overall state for State Scenes (Good morning, Good night etc).

**Comment by josecarlosmoimaz** [comment]
same here

**Comment by markand80** [comment]
I experience the same problem. Fresh install of Raspberry Pi OS Lite (May 7th 2021 version, Kernel version: 5.10) on RPi Mod 3 with HB for Raspberry PiOS. HC2 4.600. Would be great to have this resolved as Virtual Devices are a great way to wrap already existing  HC2 scenes, avoiding you to have to recreate them in Apple Home to be able to use Siri activation.

**Comment by ilcato** [comment]
@Cameleon99 @josecarlosmoimaz @markand80 can you test the beta version on an HC2 and see if the VD are working?
Use `sudo npm install -g homebridge-fibaro-home-center@beta`
Thanks

**Comment by ilcato** [comment]
Put it in the latest release
