### ISSUE TITLE
HC3 nice device not recognized

### ISSUE THREAD

**Issue by tuxtof** [ilcato/homebridge-fibaro-home-center#56]
Hi

I just install your module in homebridge to connect to my HC3

I have 18 nice devices and two quick app, only the quick app are discover in the home app 

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/180613/121701002-c27e5680-cad0-11eb-9cf4-94982824c4e3.png">

34 35 are recognized
37 38 not recognized

is it normal

my install

Homebridge v1.3.4
homebridge-fibaro-hc3  v1.1.14
figaro FW 5.070.42

**Comment by redeemer666** [comment]
I think this is similar to my issue #53. @tuxtof if you feel brave, you can try the workaround, just make sure to choose the correct section. It worked on my garage door from “nice” brand
