### ISSUE TITLE
Error during syncronization

### ISSUE THREAD

**Issue by Berti321** [ilcato/homebridge-fibaro-home-center#58]
Hi I installed the homebridge today and I always get this error. I have copied the certificate to the folder. What am I doing wrong? I would be grateful for a tip

I use Docker

---------------------------------------------------------------------------------

Starting to advertise 'Homebridge CD99 7A05' using bonjour-hap backend!
[6/14/2021, 2:17:06 PM] Homebridge v1.3.4 (Homebridge CD99) is running on port 53471.
[6/14/2021, 2:17:06 PM] [FibaroHC3] Error getting data from Home Center:  Error: getaddrinfo ENOTFOUND hc3-0000XXXX.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'hc3-0000XXXX.local',
  response: undefined
}
(node:369) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND hc3-0000XXXX.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ilcato** [comment]
https not working with docker plugin implementation.
Please use `host` parameter and not `url`.
Or do not use docker.
