### ISSUE TITLE
Fibaro plug not supported

### ISSUE THREAD

**Issue by amatt09** [ilcato/homebridge-fibaro-home-center#64]
I have three fibaro brand plugs in my bedroom, they do not show up on the Home app on iOS or in the logs of homebridge. all of my other non fibaro plugs show and work fine. 

Fibaro HC2
Latest homebridge version
all plugins are up to date.
using separate account on HC2 for homebridge (yes I have made sure the device is checked for access)

**Comment by ilcato** [comment]
@amatt09, which version of the plugs do you have?

**Comment by Damianod27** [comment]
If you added new devices and created the profile before, the new devices will not be visible. You must go to the HC2 user profile that you are using for Homebridge and select it.

**Comment by amatt09** [comment]
> @amatt09, which version of the plugs do you have?

@ilcato Version 4.0 and 4.1

**Comment by amatt09** [comment]
@Damianod27 the devices are already added to the user account in HC2 that I use for homebridge. It does not show the device in homebridge as an accessory.

**Comment by ilcato** [comment]
> > @amatt09, which version of the plugs do you have?
> 
> @ilcato Version 4.0 and 4.1

@amatt09 are you able to tell me the `type` of the device using the REST API ?
