### ISSUE TITLE
Error getting data from Home Center with version 1.2.2

### ISSUE THREAD

**Issue by richardtuboly** [ilcato/homebridge-fibaro-home-center#70]
Hello,

after updating to the new version the plugin stopped working.
I don't see the panels/climate endpoint on the swagger/docs.

[09/12/2021, 19:32:21] [FibaroHC] Error getting data from Home Center:  Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  status: 501,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 501,
      statusMessage: 'Not Implemented',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      text: '',
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      _enableHttp2: false,
      _agent: false,
      _formData: null,
      method: 'GET',
      url: 'http://192.168.0.5/api/panels/climate?detailed=false',
      _header: [Object],
      header: [Object],
      writable: true,
      _redirects: 0,
      _maxRedirects: 5,
      cookies: '',
      qs: {},
      _query: [],
      qsRaw: [],
      _redirectList: [],
      _streamRequest: false,
      throttle: [Throttle],
      serial: false,
      _maskedEnd: [Function (anonymous)],
      end: [Function (anonymous)],
      _ca: undefined,
      _maskedCallback: [Function (anonymous)],
      req: [ClientRequest],
      protocol: 'http:',
      host: '192.168.0.5',
      _endCalled: true,
      _callback: [Function: cleanup],
      _fullfilledPromise: [Promise],
      res: [IncomingMessage],
      _resBuffered: true,
      response: [Circular *1],
      called: true,
      [Symbol(kCapture)]: false
    },
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /api/panels/climate?detailed=false HTTP/1.1\r\n' +
        'Host: 192.168.0.5\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Authorization: Basic XXX=\r\n' +
        'accept: json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/panels/climate?detailed=false',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.0.5',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: '',
    body: {},
    files: undefined,
    buffered: true,
    headers: {
      server: 'nginx/1.8.0',
      date: 'Thu, 09 Dec 2021 18:32:21 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    header: {
      server: 'nginx/1.8.0',
      date: 'Thu, 09 Dec 2021 18:32:21 GMT',
      'transfer-encoding': 'chunked',
      connection: 'close'
    },
    statusCode: 501,
    status: 501,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    error: Error: cannot GET /api/panels/climate?detailed=false (501)
        at Response.toError (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:95:15)
        at Response._setStatusProperties (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/response-base.js:126:48)
        at new Response (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/response.js:41:8)
        at Request._emitResponse (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:928:20)
        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:38)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) {
      status: 501,
      text: '',
      method: 'GET',
      path: '/api/panels/climate?detailed=false'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: '',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    pipe: [Function (anonymous)],
    [Symbol(kCapture)]: false
  }
}
(node:11411) UnhandledPromiseRejectionWarning: Error: Not Implemented
    at Request.callback (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-fibaro-home-center/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ilcato** [comment]
@richardtuboly, which home center do you have ? Can you share the first 4 characters of your serial number (should be HC2- or HC3- or something similar) ?

**Comment by richardtuboly** [comment]
HCL (Home Center Lite)

**Comment by ilcato** [comment]
@richardtuboly , can you update to version 1.2.3 ?

**Comment by richardtuboly** [comment]
thank you! works perfectly now.
