### ISSUE TITLE
Dimmer issue when controlling device from Homekit

### ISSUE THREAD

**Issue by jimbju** [ilcato/homebridge-fibaro-home-center#71]
Hi,

Verisons:
Homebridge v1.3.8
homebridge-fibaro-home-center v1.2.3
iOS v15.1.1

I'm experiencing the same issue as in issue [#48](https://github.com/ilcato/homebridge-fibaro-home-center/issues/48), which has been closed.

I have a dimmer, which is working fine in the Fibaro app (web UI) and in the Homebridge app (controlling the dimmer from the "accessories" page works fine). However, if I adjust the dimmer using the Apple Home app, the lights flicker and when I release the dimmer (at let's say 60%) it immediately goes back to the original value.

This is what it looks like in the status page:
![image](https://user-images.githubusercontent.com/5991645/145677600-12d7ff7b-cd5b-4e32-a0e0-613952659414.png)

I'd be happy to troubleshoot and provide logs and what not if I'm provided some guidance!
Thanks!

Best regards,
Jim

**Comment by ilcato** [comment]
Can you test version 1.2.4 ?

**Comment by au-james** [comment]
I have this same issue. When adjusting dimmer level, dimmers jump for less than a second to the selected level, then revert to the original dimming level. Turning off/on works as expected.
![image](https://user-images.githubusercontent.com/96862365/147731867-689985a5-5e17-45dd-ba9c-acd073931190.png)

Homebridge v1.3.9
HC v4.620
homebridge-fibaro-home-center v1.2.4

The old plug homebridge-fibaro-hc2 v2.4.3 works ok.

**Comment by ilcato** [comment]
@jimbju, can you test 1.2.7-beta.5 ?
@oxystin, it contains your fix.

**Comment by au-james** [comment]
I installed v1.2.7 - Latest. Looks like this is fixed. Thanks!
