### ISSUE TITLE
Issue in version 1.2.3

### ISSUE THREAD

**Issue by Damianod27** [ilcato/homebridge-fibaro-home-center#73]
The latest version 1.2.3 has led to the destruction of the Home Application. All my scenes and automations containing Fibaro devices have been removed. Fibaro is 90% of all my devices. All Fibaro devices that were grouped are now in one room. It will take me several evenings to restore it to its original state. I'm broken :-(

Homebridge Version 1.3.8

![2021-12-15 014021](https://user-images.githubusercontent.com/79320859/146102325-d42acbea-1c0b-4328-8a0e-8eccc1fb2cae.png)
![2021-12-15 014111](https://user-images.githubusercontent.com/79320859/146102327-d7cbc208-2218-432d-9475-41f3c3ba89b0.png)

**Comment by ilcato** [comment]
@Damianod27 can you try reversing to v1.2.2 ?

**Comment by Damianod27** [comment]
Thank you for your reply.  Yes of course I went back to version 1.2.2 and everything is ok. I also always make a copy of the Micro SD card before updating.  Restoring a copy and reverting the plug-in to version 1.2.2 did not fix my Home application.  I sat till 5:00 am yesterday morning and recreated most of my house.

**Comment by ilcato** [comment]
@Damianod27 , I'm very sorry. I'm looking for the bug in 1.2.3. It doesn't appear in my installation. Will come back to you as soon as it is solved.

**Comment by Damianod27** [comment]
You have nothing to apologize for.  These things happen.  I don't blame you.  Thank you for creating the plugin and keeping it alive.

**Comment by ilcato** [comment]
@Damianod27 do you have virtual devices ? Are you on an HC2 ?

**Comment by Damianod27** [comment]
Yes I have HC2.  Software 4.6.  Yes, I have one virtual device.  It is used to restart HC2.![image](https://user-images.githubusercontent.com/79320859/146199478-92becdc0-9104-49e6-a08e-6c08db9bd45c.jpeg)

**Comment by ilcato** [comment]
Version 1.2.4 should solve the problem. Thanks to @rafalantas for the testing support.

**Comment by Damianod27** [comment]
Thank you very much. Will test over the weekend.

**Comment by ilcato** [comment]
@Damianod27, where you able to test it?

**Comment by Damianod27** [comment]
I'm sorry, I forgot.  Yes, everything is ok.

**Comment by ilcato** [comment]
Thanks
