### ISSUE TITLE
only Fibaro light switches working after update 1.2.3

### ISSUE THREAD

**Issue by rafalantas** [ilcato/homebridge-fibaro-home-center#74]
it is weird issue.. I have multiple Fibaro device switches, plugs etc, temperature sensors etc. 

But after the update I can only trigger light switches from Home App or from HB webpage. Logs are not showing anything 

Reverted to 1.2.2 and everything is back working

**Comment by ilcato** [comment]
@rafalantas can you test the beta version? `nom install -g homebridge-fibaro-home-center@beta`

**Comment by rafalantas** [comment]
i have installed 1.2.4 beta
<img width="515" alt="Zrzut ekranu 2021-12-15 o 09 40 57" src="https://user-images.githubusercontent.com/12709608/146153211-ee45cedb-1bfd-467c-a5bd-c74f12699628.png">

restarted HB still the same :( normal Fibaro light switch are working fine. RGB modules or plug not

**Comment by ilcato** [comment]
@rafalantas do you have virtual devices ?

**Comment by ilcato** [comment]
@rafalantas can you install latest beta ?

**Comment by rafalantas** [comment]
installed the same :( I found something in the logs 

15/12/2021, 12:38:29] [FibaroHC] Error getting data from Home Center:  Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:462:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at new FibaroAccessory (/usr/lib/node_modules/homebridge-fibaro-home-center/src/fibaroAccessory.ts:228:60)
    at FibaroHC.addAccessory (/usr/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:226:18)
    at /usr/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:161:14
    at Array.map (<anonymous>)
    at FibaroHC.LoadAccessories (/usr/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:153:13)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-home-center/src/platform.ts:131:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

and yes I have few virtual devices.

**Comment by rafalantas** [comment]
so installed beta 1 and rebooted HB

from Home App I could turn on switch but couldn't turn on RGB. Reverted back to 1.2.2 everything is OK

**Comment by rafalantas** [comment]
let me check something ;)

**Comment by ilcato** [comment]
@rafalantas can you install latest beta ?

**Comment by rafalantas** [comment]
installed and looking good. I can control RGB and plugs and normal switches

**Comment by ilcato** [comment]
@rafalantas, ok. will ask you another test in a few minutes If you are available.

**Comment by rafalantas** [comment]
sure tell me what to install and I'll do that

**Comment by ilcato** [comment]
@rafalantas can you install latest beta ?

**Comment by rafalantas** [comment]
not working again

**Comment by ilcato** [comment]
ok, it's the virtual device logic. D you have an HC2?

**Comment by rafalantas** [comment]
Yes I do have HC2 and few virtual devices

**Comment by ilcato** [comment]
@rafalantas can you install latest beta ?
Check also, please, if the virtual devices are working in homebridge.
Thanks

**Comment by rafalantas** [comment]
installed beta 4 the same not working RGB and plug ;(

**Comment by ilcato** [comment]
@rafalantas can you test the new beta ?
Unfortunately I must remove VD support because cannot test it on an HC2.
In a near future I will ask you for help in testing the feature.

**Comment by rafalantas** [comment]
@ilcato Beta 5 is OK :)

**Comment by ilcato** [comment]
Ok, I just published version 1.2.4 final

**Comment by ilcato** [comment]
Thanks
