### ISSUE TITLE
Thermostat not shown in HomeKit

### ISSUE THREAD

**Issue by frimar75** [ilcato/homebridge-fibaro-home-center#78]
I have 2 Eurotronic Spirits running and one of them is not correctly shown in the home app. It just shows the temperature but the Thermostat-device itself is not in the home app, so can‘t influence the temperature via home app. The other Eurotronic device is shown correctly.

**Comment by ilcato** [comment]
@frimar75, which version of the plugin do you have ? In the last one I removed the support for the single thermostats in favour of the climate zones.

**Comment by frimar75** [comment]
Hi, it’s v 1.2.4. but as I said, one thermostat is shown as usual, the other one isn‘t and I just recognised, that also my Fibaro heat isn‘t shown, I just can see the actual temperature but I guess, I can not influence it ….

Von meinem iPad gesendet

Am 22.12.2021 um 10:14 schrieb ilcato ***@***.***>:

﻿

@frimar75<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrimar75&data=04%7C01%7C%7Cc8329fdd77b941e546f808d9c52b6943%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637757612497014071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=patLBamGesYQ%2FlT1s2cjPiwTh1BlQNazfwfVF6hSNg8%3D&reserved=0>, which version of the plugin do you have ? In the last one I removed the support for the single thermostats in favour of the climate zones.

**Comment by ilcato** [comment]
@frimar75 in version 1.2.4 no support for thermostats. Probably your cached accessories is dirty. Try to remove the specific accessories from it (you can do it via homebridge UI).

**Comment by frimar75** [comment]
Okay, that seemed to be the problem, now everything works, thanks!
