### ISSUE TITLE
Radiator thermostat mode ‘OFF’ not detected

### ISSUE THREAD

**Issue by wilbertsmits** [ilcato/homebridge-fibaro-home-center#79]
Hi, 

First: I’m really happy with the plug-in. Keep up the good work!

I have an issue with radiator thermostats (Eurotronic Spirit): when I change the operating mode to ‘OFF’ it’s not detected in Homebridge. It displays the ‘old’ temperature. 
I tried changing the mode via ‘climate’ and the device itself. Both don’t result in updating the state in Homebridge.

cheers,

Wilbert

**Comment by ilcato** [comment]
@wilbertsmits which version of the plugin are you using? In the latest version there's no support for single thermostats, only for climate zones.

**Comment by wilbertsmits** [comment]
I'm using the latest version and am aware that only climate is supported. But changing in climate didn't result in an update of the item in Homebridge.
I would love to see single thermostats working so I can do all the 'climate' management in Apple Home and bypassing Fibaro climate. Is that something you want to place on the backlog?

**Comment by ilcato** [comment]
@wilbertsmits, do you see something strange in the log? Can you share it?
