### ISSUE TITLE
How to update from v1.1.14

### ISSUE THREAD

**Issue by TimE90** [ilcato/homebridge-fibaro-home-center#83]
I've installed and configured plugin version 1.1.14.

What's the best way to update without loosing all devices and configurations?

**Comment by TimE90** [comment]
For better explanation: I've installed _homebridge-fibaro-hc3 v1.1.14_. I don't know how to update this because the repository doesn't exist anymore?

**Comment by TimE90** [comment]
Maybe it's possible through editing cachedAccessories and change "[{"plugin":"homebridge-fibaro-hc3","platform":"FibaroHC3"" to "[{"plugin":"homebridge-fibaro-home-center","platform":"FibaroHC"?

**Comment by ilcato** [comment]
> Maybe it's possible through editing cachedAccessories and change "[{"plugin":"homebridge-fibaro-hc3","platform":"FibaroHC3"" to "[{"plugin":"homebridge-fibaro-home-center","platform":"FibaroHC"?

Not sure it is possible.
