### ISSUE TITLE
Blinds module activated when opening het accessory page

### ISSUE THREAD

**Issue by FBerriere** [ilcato/homebridge-fibaro-home-center#85]
Everytime i open a room in the accessory page within homebridge, the blinds (Fibaro Roller Shutter modules) in that room receive some sort of signal. I can hear the relays of the modules clicking. The plugin sends the last known value to the modules: i tested and confirmed this by:
- changing the position of the blinds in homebridge
- going to another room and back to the room with the blinds (position doens't change, you only hear the delays for blinds that are completely open or closed)
- Change their position straight from the fibaro
- Change rapidly to another room in homebridge and back to the room with blinds, before the blinds' state is updated in homebridge
This time the blinds do change position, to the values last known by homebridge / fibaro plugin.

I used homebridge and the plugin for a couple of years now, this problem only arrised today after i decided to upgrade the system.

**Comment by ilcato** [comment]
@FBerriere, which update are you referring to ?

**Comment by ilcato** [comment]
stale
