### ISSUE TITLE
Virtual devices

### ISSUE THREAD

**Issue by alloploid** [ilcato/homebridge-fibaro-home-center#86]
Hi,

Do you plan to support Virtual Devices (HC2)?

**Comment by kot-925** [comment]
Also interested in this question!

**Comment by ilcato** [comment]
Not for now

**Comment by Franco268** [comment]
and what about QA?

**Comment by alloploid** [comment]
It should be possible to create Fibaro scenes that interact with the virtual device, then expose those scenes as bistable switches to Homebridge
