### ISSUE TITLE
Power Consumption

### ISSUE THREAD

**Issue by mol7os** [ilcato/homebridge-fibaro-home-center#94]
Hi, 
maybe I missed this in any description but would it be possible to get "Power Consumption" state as well? 
I am using different Homebridge instances, one as an example within the iobroker (only for internal purposes). 
In this implementation, it seems that the "power" value will not collected by the plugin. Is there a chance to request this value?

**Comment by mkz212** [comment]
It seems to me that HomeKit does not offer such a possibility so far. This is not a limitation of this plugin but the Apple HomeKit plugin.
