### ISSUE TITLE
about com.fibaro.fanMode

### ISSUE THREAD

**Issue by baduxiyang** [ilcato/homebridge-fibaro-home-center#96]
Hello, will version 1.2.8 be updated in the near future? Is there a solution to the problem of air conditioning fan?

Device kind:com. fibaro. fanMode

Thank you

**Comment by baduxiyang** [comment]
If I need assistance, I can send a remote account for assistance

**Comment by baduxiyang** [comment]
> @baduxiyang，有什么问题吗？

This is not displayed in homebridge ,thank you!

**Comment by mkz212** [comment]
Please fill #157
